"""
flask API server
serves risk predictions from the trained model
"""

from flask import Flask, request, jsonify
from flask_cors import CORS
import numpy as np
import pandas as pd
import geopandas as gpd
from pathlib import Path
import logging
import sys
from shapely.geometry import Point, box
from sklearn.neighbors import BallTree

# import existing modules
PROJECT_ROOT = Path(__file__).parent.parent
sys.path.insert(0, str(PROJECT_ROOT))

# import existing modules
from src.models.model_trainer import ModelTrainer
from src.data_processing.data_loader import load_road_network
from src.data_processing.spatial_join_fast import perform_spatial_join_fast
from src.feature_engineering.feature_creator import create_segment_features
from src.feature_engineering.label_generator import generate_risk_labels

app = Flask(__name__)
CORS(app)

# initialize model trainer and load model
MODEL_PATH = PROJECT_ROOT / "outputs" / "models" / "toronto_risk_model.joblib"
model_trainer = ModelTrainer()

try:
    model_trainer.load_model(str(MODEL_PATH))
    logging.info("Model loaded successfully")
except Exception as e:
    logging.error(f"Failed to load model: {e}")
    model_trainer = None

# load pre-processed road network with predictions
# this should be generated by running the full pipeline once
PREPROCESSED_DATA_PATH = (
    PROJECT_ROOT / "outputs" / "reports" / "toronto_road_risk.geojson"
)
preprocessed_data = None

try:
    if PREPROCESSED_DATA_PATH.exists():
        preprocessed_data = gpd.read_file(PREPROCESSED_DATA_PATH)
        logging.info(f"Loaded {len(preprocessed_data)} pre-processed road segments")
    else:
        logging.warning(
            "Pre-processed data not found. Will process on-demand (slower)."
        )
except Exception as e:
    logging.warning(f"Could not load pre-processed data: {e}")

# Load raw road network for on-demand processing
road_network = None
try:
    data_dir = PROJECT_ROOT / "data"
    road_network = load_road_network(data_dir)
    logging.info(f"Loaded {len(road_network)} road segments")
except Exception as e:
    logging.warning(f"Could not load road network: {e}")


@app.route("/api/health", methods=["GET"])
def health_check():
    """Health check endpoint"""
    return jsonify(
        {
            "status": "healthy",
            "model_loaded": model_trainer is not None
            and model_trainer.model is not None,
            "preprocessed_data_loaded": preprocessed_data is not None,
            "road_network_loaded": road_network is not None,
            "preprocessed_segments": (
                len(preprocessed_data) if preprocessed_data is not None else 0
            ),
        }
    )


@app.route("/api/risk-predictions", methods=["POST"])
def get_risk_predictions():
    """
    Get risk predictions for a geographic region

    Request body:
    {
        "north": float,
        "south": float,
        "east": float,
        "west": float
    }
    """
    if model_trainer is None or model_trainer.model is None:
        return jsonify({"error": "Model not loaded"}), 500

    try:
        data = request.get_json()
        north = data.get("north")
        south = data.get("south")
        east = data.get("east")
        west = data.get("west")

        # use pre-processed data if available
        if preprocessed_data is not None:
            bbox = box(west, south, east, north)
            segments_in_bbox = preprocessed_data[
                preprocessed_data.geometry.intersects(bbox)
            ]

            # limit to 500 segments to prevent timeout and reduce response size
            # prioritize high-risk segments first
            if len(segments_in_bbox) > 500:
                # sort by risk level (high > medium > low) and take top 500
                risk_priority = {"high": 3, "medium": 2, "low": 1}
                segments_in_bbox = segments_in_bbox.copy()
                segments_in_bbox["_risk_priority"] = segments_in_bbox.get(
                    "risk_label", "low"
                ).map(risk_priority)
                segments_in_bbox = segments_in_bbox.sort_values(
                    "_risk_priority", ascending=False
                ).head(500)

            results = []
            for idx, segment in segments_in_bbox.iterrows():
                # extract coordinates from geometry
                coords = _extract_coordinates(segment.geometry)

                # use pre-processed risk prediction (already computed, no need to run model again)
                risk_label = segment.get("risk_label", "low")
                confidence = segment.get("confidence", 0.5)

                result = {
                    "id": str(segment.get("segment_id", idx)),
                    "LINEAR_NAME": segment.get("LINEAR_NAME", "Unknown"),
                    "ROAD_CLASS": segment.get("ROAD_CLASS", "Unknown"),
                    "segment_length": float(segment.get("segment_length", 0)),
                    "risk_label": risk_label,
                    "confidence": float(confidence) if confidence else 0.5,
                    "num_total_crashes": int(segment.get("num_total_crashes", 0)),
                    "num_ksi_crashes": int(segment.get("num_ksi_crashes", 0)),
                    "fatality_count": int(segment.get("fatality_count", 0)),
                    "coordinates": coords[:50],  # Limit coordinates to reduce payload
                }
                results.append(result)

            logging.info(f"Returning {len(results)} segments for bbox")
            return jsonify(results)

        # fallback: process on-demand
        elif road_network is not None:
            bbox = box(west, south, east, north)
            segments_in_bbox = road_network[
                road_network.geometry.intersects(bbox)
            ].head(100)

            # this would require full data processing pipeline, but, for now, returning basic info without predictions
            results = []
            for idx, segment in segments_in_bbox.iterrows():
                coords = _extract_coordinates(segment.geometry)

                result = {
                    "id": str(idx),
                    "LINEAR_NAME": segment.get("LINEAR_NAME", "Unknown"),
                    "ROAD_CLASS": segment.get("ROAD_CLASS", "Unknown"),
                    "segment_length": float(segment.get("segment_length", 0)),
                    "risk_label": "low",  # default, would need full processing
                    "confidence": 0.5,
                    "num_total_crashes": 0,
                    "num_ksi_crashes": 0,
                    "fatality_count": 0,
                    "coordinates": coords[:50],
                }
                results.append(result)

            return jsonify(results)
        else:
            return jsonify({"error": "Road network not loaded"}), 500

    except Exception as e:
        logging.error(f"Error in risk predictions: {e}")
        import traceback

        traceback.print_exc()
        return jsonify({"error": str(e)}), 500


def _extract_coordinates(geometry):
    """Extract coordinates from geometry for JSON serialization"""
    coords = []
    try:
        # Handle multi-part geometries (MultiLineString, MultiPoint, etc.)
        # Check for 'geoms' attribute first to avoid trying .coords on multi-part geometries
        if hasattr(geometry, "geoms") and geometry.geoms:
            for geom in geometry.geoms:
                # Each sub-geometry should be a LineString, Point, etc.
                if hasattr(geom, "coords"):
                    for coord in geom.coords:
                        if len(coord) >= 2:
                            lon, lat = coord[0], coord[1]
                            coords.append({"latitude": lat, "longitude": lon})
        # Handle single-part geometries (LineString, Point, etc.)
        elif hasattr(geometry, "coords"):
            for coord in geometry.coords:
                if len(coord) >= 2:
                    lon, lat = coord[0], coord[1]
                    coords.append({"latitude": lat, "longitude": lon})
        # Handle Polygon - get exterior coordinates
        elif hasattr(geometry, "exterior"):
            return _extract_coordinates(geometry.exterior)
        # Handle Polygon with xy attribute
        elif hasattr(geometry, "xy"):
            x_coords, y_coords = geometry.xy
            for lon, lat in zip(x_coords, y_coords):
                coords.append({"latitude": lat, "longitude": lon})
    except (AttributeError, TypeError, IndexError) as e:
        # Suppress warnings for expected geometry structure differences
        # These are handled by the code above, no need to log
        pass
    except Exception as e:
        # Only log truly unexpected errors, and at debug level
        logging.debug(f"Error extracting coordinates: {e}")
    return coords


def _predict_segment_risk(segment, model_trainer):
    """
    Get risk prediction from model for a segment

    Args:
        segment: GeoDataFrame row with segment data
        model_trainer: Loaded ModelTrainer instance

    Returns:
        Tuple of (risk_label, probabilities_dict, confidence) or (None, None, None) if prediction fails
    """
    try:
        # Check if segment has the required feature columns
        if not model_trainer.feature_columns:
            return None, None, None

        # Create a DataFrame with just this segment
        segment_df = pd.DataFrame([segment])

        # Extract features (only those used by the model)
        feature_data = {}
        for col in model_trainer.feature_columns:
            if col in segment_df.columns:
                value = segment_df[col].iloc[0]
                # Convert to numeric, handling various types
                if pd.isna(value):
                    feature_data[col] = 0.0
                else:
                    try:
                        feature_data[col] = float(value)
                    except (ValueError, TypeError):
                        feature_data[col] = 0.0
            else:
                feature_data[col] = 0.0

        X = pd.DataFrame([feature_data])

        for col in model_trainer.feature_columns:
            if col not in X.columns:
                X[col] = 0.0

        X = X[model_trainer.feature_columns]

        # scale features
        X_scaled = model_trainer.scaler.transform(X)

        # get prediction and probabilities
        prediction_encoded = model_trainer.model.predict(X_scaled)[0]
        probabilities_encoded = model_trainer.model.predict_proba(X_scaled)[0]

        risk_label = model_trainer.label_encoder.inverse_transform(
            [prediction_encoded]
        )[0]

        class_order = model_trainer.label_encoder.classes_
        probabilities = {
            "low": float(probabilities_encoded[0]),
            "medium": float(probabilities_encoded[1]),
            "high": float(probabilities_encoded[2]),
        }

        # Confidence is the maximum probability
        confidence = float(np.max(probabilities_encoded))

        return risk_label, probabilities, confidence

    except Exception as e:
        logging.warning(f"Error predicting segment risk: {e}")
        import traceback

        traceback.print_exc()
        return None, None, None


@app.route("/api/risk-prediction", methods=["POST"])
def get_risk_prediction():
    """
    Get risk prediction for a specific location

    Request body:
    {
        "latitude": float,
        "longitude": float
    }
    """
    if model_trainer is None or model_trainer.model is None:
        return jsonify({"error": "Model not loaded"}), 500

    try:
        data = request.get_json()
        lat = data.get("latitude")
        lon = data.get("longitude")

        point = Point(lon, lat)

        # Use pre-processed data if available
        if preprocessed_data is not None:
            # Find nearest segment
            from shapely.ops import nearest_points

            nearest_idx = None
            min_distance = float("inf")

            for idx, segment in preprocessed_data.iterrows():
                distance = point.distance(segment.geometry)
                if distance < min_distance:
                    min_distance = distance
                    nearest_idx = idx

            if nearest_idx is not None and min_distance < 0.01:  # Within ~1km
                segment = preprocessed_data.loc[nearest_idx]

                risk_label = segment.get("risk_label", "low")
                confidence = segment.get("confidence", 0.5)
                probabilities = None

                if model_trainer and model_trainer.model is not None:
                    try:
                        prediction, probs, model_confidence = _predict_segment_risk(
                            segment, model_trainer
                        )
                        if prediction is not None:
                            risk_label = prediction
                            confidence = model_confidence
                            probabilities = probs
                    except Exception as e:
                        logging.debug(f"Could not get model prediction: {e}")

                if probabilities is None:
                    if risk_label == "high":
                        probabilities = {"low": 0.1, "medium": 0.1, "high": 0.8}
                    elif risk_label == "medium":
                        probabilities = {"low": 0.2, "medium": 0.7, "high": 0.1}
                    else:
                        probabilities = {"low": 0.8, "medium": 0.15, "high": 0.05}

                segment_info = {
                    "id": str(segment.get("segment_id", nearest_idx)),
                    "LINEAR_NAME": segment.get("LINEAR_NAME", "Unknown"),
                    "ROAD_CLASS": segment.get("ROAD_CLASS", "Unknown"),
                    "segment_length": float(segment.get("segment_length", 0)),
                    "num_total_crashes": int(segment.get("num_total_crashes", 0)),
                    "num_ksi_crashes": int(segment.get("num_ksi_crashes", 0)),
                    "fatality_count": int(segment.get("fatality_count", 0)),
                    "coordinates": _extract_coordinates(segment.geometry),
                }

                response = {
                    "riskLevel": risk_label,
                    "confidence": float(confidence),
                    "probabilities": probabilities,
                    "segmentInfo": segment_info,
                }

                return jsonify(response)

        response = {
            "riskLevel": "low",
            "confidence": 0.5,
            "probabilities": {"low": 0.8, "medium": 0.15, "high": 0.05},
            "segmentInfo": None,
        }

        return jsonify(response)

    except Exception as e:
        logging.error(f"Error in risk prediction: {e}")
        import traceback

        traceback.print_exc()
        return jsonify({"error": str(e)}), 500


if __name__ == "__main__":
    logging.basicConfig(level=logging.INFO)
    app.run(host="0.0.0.0", port=8000, debug=False, use_reloader=False, threaded=False)
