"""
flask API server
serves risk predictions from the trained model
"""

from flask import Flask, request, jsonify, render_template_string
from flask_cors import CORS
import numpy as np
import pandas as pd
import geopandas as gpd
from pathlib import Path
import logging
import sys
from shapely.geometry import Point, box
from sklearn.neighbors import BallTree

# import existing modules
PROJECT_ROOT = Path(__file__).parent.parent
sys.path.insert(0, str(PROJECT_ROOT))

# import existing modules
from src.models.model_trainer import ModelTrainer
from src.data_processing.data_loader import load_road_network
from src.data_processing.spatial_join_fast import perform_spatial_join_fast
from src.feature_engineering.feature_creator import create_segment_features
from src.feature_engineering.label_generator import generate_risk_labels

# import config constants
try:
    from config import COLLISION_COLUMNS, KSI_COLUMNS
except ImportError:
    # Fallback if config import fails
    COLLISION_COLUMNS = {
        'latitude': 'LAT_WGS84',
        'longitude': 'LONG_WGS84',
        'date': 'OCC_DATE',
        'time': 'OCC_HOUR',
        'injury': 'INJURY_COLLISIONS',
        'fatalities': 'FATALITIES'
    }
    KSI_COLUMNS = {
        'latitude': 'LATITUDE',
        'longitude': 'LONGITUDE',
        'date': 'DATE',
        'time': 'TIME',
        'injury': 'INJURY',
        'fatalities': 'FATAL_NO'
    }

app = Flask(__name__)
CORS(app)

# initialize model trainer and load model
MODEL_PATH = PROJECT_ROOT / "outputs" / "models" / "toronto_risk_model.joblib"
model_trainer = ModelTrainer()

try:
    model_trainer.load_model(str(MODEL_PATH))
    logging.info("Model loaded successfully")
except Exception as e:
    logging.error(f"Failed to load model: {e}")
    model_trainer = None

# load pre-processed road network with predictions
# this should be generated by running the full pipeline once
# Try multiple possible locations
PREPROCESSED_DATA_PATHS = [
    PROJECT_ROOT / "outputs" / "reports" / "toronto_road_risk.geojson",
    PROJECT_ROOT / "outputs" / "maps" / "toronto_road_risk.geojson",
]
preprocessed_data = None

for path in PREPROCESSED_DATA_PATHS:
    try:
        if path.exists():
            preprocessed_data = gpd.read_file(path)
            logging.info(f"Loaded {len(preprocessed_data)} pre-processed road segments from {path}")
            break
    except Exception as e:
        logging.warning(f"Could not load pre-processed data from {path}: {e}")
        continue

if preprocessed_data is None:
    logging.warning("Pre-processed data not found in any expected location.")

# Load raw road network for on-demand processing
road_network = None
try:
    data_dir = PROJECT_ROOT / "data"
    road_network = load_road_network(data_dir)
    logging.info(f"Loaded {len(road_network)} road segments")
except Exception as e:
    logging.warning(f"Could not load road network: {e}")


@app.route("/api/health", methods=["GET"])
def health_check():
    """Health check endpoint"""
    return jsonify(
        {
            "status": "healthy",
            "model_loaded": model_trainer is not None
            and model_trainer.model is not None,
            "preprocessed_data_loaded": preprocessed_data is not None,
            "road_network_loaded": road_network is not None,
            "preprocessed_segments": (
                len(preprocessed_data) if preprocessed_data is not None else 0
            ),
        }
    )


@app.route("/api/risk-predictions", methods=["POST"])
def get_risk_predictions():
    """
    Get risk predictions for a geographic region

    Request body:
    {
        "north": float,
        "south": float,
        "east": float,
        "west": float
    }
    """
    if model_trainer is None or model_trainer.model is None:
        return jsonify({"error": "Model not loaded"}), 500

    try:
        data = request.get_json()
        north = data.get("north")
        south = data.get("south")
        east = data.get("east")
        west = data.get("west")

        # use pre-processed data if available
        if preprocessed_data is not None:
            bbox = box(west, south, east, north)
            segments_in_bbox = preprocessed_data[
                preprocessed_data.geometry.intersects(bbox)
            ]

            # limit to 500 segments to prevent timeout and reduce response size
            # prioritize high-risk segments first
            if len(segments_in_bbox) > 500:
                # sort by risk level (high > medium > low) and take top 500
                risk_priority = {"high": 3, "medium": 2, "low": 1}
                segments_in_bbox = segments_in_bbox.copy()
                segments_in_bbox["_risk_priority"] = segments_in_bbox.get(
                    "risk_label", "low"
                ).map(risk_priority)
                segments_in_bbox = segments_in_bbox.sort_values(
                    "_risk_priority", ascending=False
                ).head(500)

            results = []
            for idx, segment in segments_in_bbox.iterrows():
                # extract coordinates from geometry
                coords = _extract_coordinates(segment.geometry)

                # use pre-processed risk prediction (already computed, no need to run model again)
                risk_label = segment.get("risk_label", "low")
                confidence = segment.get("confidence", 0.5)

                result = {
                    "id": str(segment.get("segment_id", idx)),
                    "LINEAR_NAME": segment.get("LINEAR_NAME", "Unknown"),
                    "ROAD_CLASS": segment.get("ROAD_CLASS", "Unknown"),
                    "segment_length": float(segment.get("segment_length", 0)),
                    "risk_label": risk_label,
                    "confidence": float(confidence) if confidence else 0.5,
                    "num_total_crashes": int(segment.get("num_total_crashes", 0)),
                    "num_ksi_crashes": int(segment.get("num_ksi_crashes", 0)),
                    "fatality_count": int(segment.get("fatality_count", 0)),
                    "coordinates": coords[:50],  # Limit coordinates to reduce payload
                }
                results.append(result)

            logging.info(f"Returning {len(results)} segments for bbox")
            return jsonify(results)

        # fallback: process on-demand
        elif road_network is not None:
            bbox = box(west, south, east, north)
            segments_in_bbox = road_network[
                road_network.geometry.intersects(bbox)
            ].head(100)

            # this would require full data processing pipeline, but, for now, returning basic info without predictions
            results = []
            for idx, segment in segments_in_bbox.iterrows():
                coords = _extract_coordinates(segment.geometry)

                result = {
                    "id": str(idx),
                    "LINEAR_NAME": segment.get("LINEAR_NAME", "Unknown"),
                    "ROAD_CLASS": segment.get("ROAD_CLASS", "Unknown"),
                    "segment_length": float(segment.get("segment_length", 0)),
                    "risk_label": "low",  # default, would need full processing
                    "confidence": 0.5,
                    "num_total_crashes": 0,
                    "num_ksi_crashes": 0,
                    "fatality_count": 0,
                    "coordinates": coords[:50],
                }
                results.append(result)

            return jsonify(results)
        else:
            return jsonify({"error": "Road network not loaded"}), 500

    except Exception as e:
        logging.error(f"Error in risk predictions: {e}")
        import traceback

        traceback.print_exc()
        return jsonify({"error": str(e)}), 500


def _extract_coordinates(geometry):
    """Extract coordinates from geometry for JSON serialization"""
    coords = []
    try:
        # Handle multi-part geometries (MultiLineString, MultiPoint, etc.)
        # Check for 'geoms' attribute first to avoid trying .coords on multi-part geometries
        if hasattr(geometry, "geoms") and geometry.geoms:
            for geom in geometry.geoms:
                # Each sub-geometry should be a LineString, Point, etc.
                if hasattr(geom, "coords"):
                    for coord in geom.coords:
                        if len(coord) >= 2:
                            lon, lat = coord[0], coord[1]
                            coords.append({"latitude": lat, "longitude": lon})
        # Handle single-part geometries (LineString, Point, etc.)
        elif hasattr(geometry, "coords"):
            for coord in geometry.coords:
                if len(coord) >= 2:
                    lon, lat = coord[0], coord[1]
                    coords.append({"latitude": lat, "longitude": lon})
        # Handle Polygon - get exterior coordinates
        elif hasattr(geometry, "exterior"):
            return _extract_coordinates(geometry.exterior)
        # Handle Polygon with xy attribute
        elif hasattr(geometry, "xy"):
            x_coords, y_coords = geometry.xy
            for lon, lat in zip(x_coords, y_coords):
                coords.append({"latitude": lat, "longitude": lon})
    except (AttributeError, TypeError, IndexError) as e:
        # Suppress warnings for expected geometry structure differences
        # These are handled by the code above, no need to log
        pass
    except Exception as e:
        # Only log truly unexpected errors, and at debug level
        logging.debug(f"Error extracting coordinates: {e}")
    return coords


def _predict_segment_risk(segment, model_trainer):
    """
    Get risk prediction from model for a segment

    Args:
        segment: GeoDataFrame row with segment data
        model_trainer: Loaded ModelTrainer instance

    Returns:
        Tuple of (risk_label, probabilities_dict, confidence) or (None, None, None) if prediction fails
    """
    try:
        # Check if segment has the required feature columns
        if not model_trainer.feature_columns:
            return None, None, None

        # Create a DataFrame with just this segment
        segment_df = pd.DataFrame([segment])

        # Extract features (only those used by the model)
        feature_data = {}
        for col in model_trainer.feature_columns:
            if col in segment_df.columns:
                value = segment_df[col].iloc[0]
                # Convert to numeric, handling various types
                if pd.isna(value):
                    feature_data[col] = 0.0
                else:
                    try:
                        feature_data[col] = float(value)
                    except (ValueError, TypeError):
                        feature_data[col] = 0.0
            else:
                feature_data[col] = 0.0

        X = pd.DataFrame([feature_data])

        for col in model_trainer.feature_columns:
            if col not in X.columns:
                X[col] = 0.0

        X = X[model_trainer.feature_columns]

        # scale features
        X_scaled = model_trainer.scaler.transform(X)

        # get prediction and probabilities
        prediction_encoded = model_trainer.model.predict(X_scaled)[0]
        probabilities_encoded = model_trainer.model.predict_proba(X_scaled)[0]

        risk_label = model_trainer.label_encoder.inverse_transform(
            [prediction_encoded]
        )[0]

        class_order = model_trainer.label_encoder.classes_
        probabilities = {
            "low": float(probabilities_encoded[0]),
            "medium": float(probabilities_encoded[1]),
            "high": float(probabilities_encoded[2]),
        }

        # Confidence is the maximum probability
        confidence = float(np.max(probabilities_encoded))

        return risk_label, probabilities, confidence

    except Exception as e:
        logging.warning(f"Error predicting segment risk: {e}")
        import traceback

        traceback.print_exc()
        return None, None, None


@app.route("/api/risk-prediction", methods=["POST"])
def get_risk_prediction():
    """
    Get risk prediction for a specific location

    Request body:
    {
        "latitude": float,
        "longitude": float
    }
    """
    if model_trainer is None or model_trainer.model is None:
        return jsonify({"error": "Model not loaded"}), 500

    try:
        data = request.get_json()
        lat = data.get("latitude")
        lon = data.get("longitude")

        point = Point(lon, lat)

        # Use pre-processed data if available
        if preprocessed_data is not None:
            # Find nearest segment
            from shapely.ops import nearest_points

            nearest_idx = None
            min_distance = float("inf")

            for idx, segment in preprocessed_data.iterrows():
                distance = point.distance(segment.geometry)
                if distance < min_distance:
                    min_distance = distance
                    nearest_idx = idx

            if nearest_idx is not None and min_distance < 0.01:  # Within ~1km
                segment = preprocessed_data.loc[nearest_idx]

                risk_label = segment.get("risk_label", "low")
                confidence = segment.get("confidence", 0.5)
                probabilities = None

                if model_trainer and model_trainer.model is not None:
                    try:
                        prediction, probs, model_confidence = _predict_segment_risk(
                            segment, model_trainer
                        )
                        if prediction is not None:
                            risk_label = prediction
                            confidence = model_confidence
                            probabilities = probs
                    except Exception as e:
                        logging.debug(f"Could not get model prediction: {e}")

                if probabilities is None:
                    if risk_label == "high":
                        probabilities = {"low": 0.1, "medium": 0.1, "high": 0.8}
                    elif risk_label == "medium":
                        probabilities = {"low": 0.2, "medium": 0.7, "high": 0.1}
                    else:
                        probabilities = {"low": 0.8, "medium": 0.15, "high": 0.05}

                segment_info = {
                    "id": str(segment.get("segment_id", nearest_idx)),
                    "LINEAR_NAME": segment.get("LINEAR_NAME", "Unknown"),
                    "ROAD_CLASS": segment.get("ROAD_CLASS", "Unknown"),
                    "segment_length": float(segment.get("segment_length", 0)),
                    "num_total_crashes": int(segment.get("num_total_crashes", 0)),
                    "num_ksi_crashes": int(segment.get("num_ksi_crashes", 0)),
                    "fatality_count": int(segment.get("fatality_count", 0)),
                    "coordinates": _extract_coordinates(segment.geometry),
                }

                response = {
                    "riskLevel": risk_label,
                    "confidence": float(confidence),
                    "probabilities": probabilities,
                    "segmentInfo": segment_info,
                }

                return jsonify(response)

        response = {
            "riskLevel": "low",
            "confidence": 0.5,
            "probabilities": {"low": 0.8, "medium": 0.15, "high": 0.05},
            "segmentInfo": None,
        }

        return jsonify(response)

    except Exception as e:
        logging.error(f"Error in risk prediction: {e}")
        import traceback

        traceback.print_exc()
        return jsonify({"error": str(e)}), 500


@app.route("/data-validation", methods=["GET"])
def data_validation_page():
    """Serve the data validation page"""
    return render_template_string(_get_data_validation_html())


def _convert_to_json_serializable(obj):
    """Convert numpy/pandas types to native Python types for JSON serialization"""
    if isinstance(obj, (np.integer, np.int64, np.int32)):
        return int(obj)
    elif isinstance(obj, (np.floating, np.float64, np.float32)):
        return float(obj)
    elif isinstance(obj, np.ndarray):
        return obj.tolist()
    elif isinstance(obj, dict):
        return {key: _convert_to_json_serializable(value) for key, value in obj.items()}
    elif isinstance(obj, list):
        return [_convert_to_json_serializable(item) for item in obj]
    elif pd.isna(obj):
        return None
    else:
        return obj


@app.route("/api/fatality-diagnostic", methods=["GET"])
def fatality_diagnostic():
    """
    Diagnostic endpoint to check why no fatalities are being counted
    Examines the actual data structure and values
    """
    try:
        # Load raw data to inspect
        data_dir = PROJECT_ROOT / "data"
        
        diagnostic_info = {
            "error": None,
            "collision_data": {},
            "ksi_data": {},
            "sample_records": {}
        }
        
        try:
            # Actually load collision and KSI data
            from src.data_processing.data_loader import load_collision_data, load_ksi_data
            
            try:
                collision_raw = load_collision_data(data_dir)
                diagnostic_info["collision_data"] = {
                    "total_records": len(collision_raw),
                    "columns": list(collision_raw.columns),
                    "fatalities_column": COLLISION_COLUMNS.get('fatalities', 'FATALITIES'),
                    "injury_column": COLLISION_COLUMNS.get('injury', 'INJURY_COLLISIONS'),
                    "has_fatalities_col": COLLISION_COLUMNS.get('fatalities', 'FATALITIES') in collision_raw.columns,
                    "has_injury_col": COLLISION_COLUMNS.get('injury', 'INJURY_COLLISIONS') in collision_raw.columns,
                }
                
                # Check what values exist in these columns
                fatalities_col = COLLISION_COLUMNS.get('fatalities', 'FATALITIES')
                injury_col = COLLISION_COLUMNS.get('injury', 'INJURY_COLLISIONS')
                
                if fatalities_col in collision_raw.columns:
                    non_zero_fatalities = collision_raw[collision_raw[fatalities_col] > 0] if pd.api.types.is_numeric_dtype(collision_raw[fatalities_col]) else collision_raw[collision_raw[fatalities_col].notna() & (collision_raw[fatalities_col].astype(str).str.lower() != '0')]
                    diagnostic_info["collision_data"]["non_zero_fatalities_count"] = len(non_zero_fatalities)
                    fatalities_stats = {}
                    if len(collision_raw) > 0:
                        value_counts = collision_raw[fatalities_col].value_counts().head(10).to_dict()
                        fatalities_stats = {
                            "total_non_null": int(collision_raw[fatalities_col].notna().sum()),
                            "unique_values": _convert_to_json_serializable(value_counts),
                            "sample_values": _convert_to_json_serializable(collision_raw[fatalities_col].head(10).tolist()),
                        }
                    else:
                        fatalities_stats = {
                            "total_non_null": 0,
                            "unique_values": {},
                            "sample_values": [],
                        }
                    diagnostic_info["collision_data"]["fatalities_column_stats"] = fatalities_stats
                
                if injury_col in collision_raw.columns:
                    fatal_in_injury = collision_raw[collision_raw[injury_col].astype(str).str.contains('Fatal', case=False, na=False)]
                    diagnostic_info["collision_data"]["fatal_in_injury_count"] = len(fatal_in_injury)
                    if len(collision_raw) > 0:
                        injury_values = collision_raw[injury_col].value_counts().head(10).to_dict()
                        diagnostic_info["collision_data"]["injury_column_unique_values"] = _convert_to_json_serializable(injury_values)
                    else:
                        diagnostic_info["collision_data"]["injury_column_unique_values"] = {}
                
                # Sample records with potential fatalities
                if fatalities_col in collision_raw.columns:
                    sample_fatal = collision_raw.nlargest(5, fatalities_col) if pd.api.types.is_numeric_dtype(collision_raw[fatalities_col]) else collision_raw.head(5)
                    diagnostic_info["sample_records"]["collision_with_fatalities"] = [
                        {
                            "fatalities_col_value": str(record.get(fatalities_col, 'N/A')),
                            "injury_col_value": str(record.get(injury_col, 'N/A')) if injury_col in record.index else 'N/A',
                            "columns_with_fatal": [col for col in record.index if 'fatal' in col.lower() or 'death' in col.lower()],
                        }
                        for idx, record in sample_fatal.iterrows()
                    ]
                
            except Exception as e:
                diagnostic_info["collision_data"]["error"] = str(e)
            
            try:
                ksi_raw = load_ksi_data(data_dir)
                diagnostic_info["ksi_data"] = {
                    "total_records": len(ksi_raw),
                    "columns": list(ksi_raw.columns),
                    "fatalities_column": KSI_COLUMNS.get('fatalities', 'FATAL_NO'),
                    "injury_column": KSI_COLUMNS.get('injury', 'INJURY'),
                    "has_fatalities_col": KSI_COLUMNS.get('fatalities', 'FATAL_NO') in ksi_raw.columns,
                    "has_injury_col": KSI_COLUMNS.get('injury', 'INJURY') in ksi_raw.columns,
                }
                
                # Check what values exist in these columns
                fatalities_col = KSI_COLUMNS.get('fatalities', 'FATAL_NO')
                injury_col = KSI_COLUMNS.get('injury', 'INJURY')
                
                if fatalities_col in ksi_raw.columns:
                    non_zero_fatalities = ksi_raw[ksi_raw[fatalities_col] > 0] if pd.api.types.is_numeric_dtype(ksi_raw[fatalities_col]) else ksi_raw[ksi_raw[fatalities_col].notna() & (ksi_raw[fatalities_col].astype(str).str.lower() != '0')]
                    diagnostic_info["ksi_data"]["non_zero_fatalities_count"] = len(non_zero_fatalities)
                    ksi_fatalities_stats = {}
                    if len(ksi_raw) > 0:
                        value_counts = ksi_raw[fatalities_col].value_counts().head(10).to_dict()
                        ksi_fatalities_stats = {
                            "total_non_null": int(ksi_raw[fatalities_col].notna().sum()),
                            "unique_values": _convert_to_json_serializable(value_counts),
                            "sample_values": _convert_to_json_serializable(ksi_raw[fatalities_col].head(10).tolist()),
                            "data_type": str(ksi_raw[fatalities_col].dtype),
                        }
                    else:
                        ksi_fatalities_stats = {
                            "total_non_null": 0,
                            "unique_values": {},
                            "sample_values": [],
                            "data_type": "unknown",
                        }
                    diagnostic_info["ksi_data"]["fatalities_column_stats"] = ksi_fatalities_stats
                
                if injury_col in ksi_raw.columns:
                    fatal_in_injury = ksi_raw[ksi_raw[injury_col].astype(str).str.contains('Fatal', case=False, na=False)]
                    diagnostic_info["ksi_data"]["fatal_in_injury_count"] = len(fatal_in_injury)
                    if len(ksi_raw) > 0:
                        injury_values = ksi_raw[injury_col].value_counts().head(10).to_dict()
                        diagnostic_info["ksi_data"]["injury_column_unique_values"] = _convert_to_json_serializable(injury_values)
                    else:
                        diagnostic_info["ksi_data"]["injury_column_unique_values"] = {}
                
                # Sample records
                if fatalities_col in ksi_raw.columns:
                    sample_fatal = ksi_raw.nlargest(5, fatalities_col) if pd.api.types.is_numeric_dtype(ksi_raw[fatalities_col]) else ksi_raw.head(5)
                    diagnostic_info["sample_records"]["ksi_with_fatalities"] = [
                        {
                            "fatalities_col_value": str(record.get(fatalities_col, 'N/A')),
                            "injury_col_value": str(record.get(injury_col, 'N/A')) if injury_col in record.index else 'N/A',
                            "columns_with_fatal": [col for col in record.index if 'fatal' in col.lower() or 'death' in col.lower()],
                        }
                        for idx, record in sample_fatal.iterrows()
                    ]
                
            except Exception as e:
                diagnostic_info["ksi_data"]["error"] = str(e)
                
        except Exception as e:
            diagnostic_info["error"] = str(e)
            import traceback
            diagnostic_info["traceback"] = traceback.format_exc()
        
        return jsonify(diagnostic_info)
    
    except Exception as e:
        logging.error(f"Error in fatality diagnostic: {e}")
        import traceback
        return jsonify({"error": str(e), "traceback": traceback.format_exc()}), 500


@app.route("/api/data-verification", methods=["GET"])
def data_verification():
    """
    Provide diagnostic information about crash data relationships
    to help verify KSI and fatality numbers
    """
    if preprocessed_data is None and road_network is None:
        return jsonify({"error": "No data available"}), 500
    
    try:
        data_source = preprocessed_data if preprocessed_data is not None else road_network
        
        # Analyze the data relationships
        total_segments = len(data_source)
        segments_with_crashes = len(data_source[data_source.get("num_total_crashes", 0) > 0]) if "num_total_crashes" in data_source.columns else 0
        segments_with_ksi = len(data_source[data_source.get("num_ksi_crashes", 0) > 0]) if "num_ksi_crashes" in data_source.columns else 0
        
        # Calculate totals
        total_crashes = int(data_source.get("num_total_crashes", 0).sum()) if "num_total_crashes" in data_source.columns else 0
        total_ksi = int(data_source.get("num_ksi_crashes", 0).sum()) if "num_ksi_crashes" in data_source.columns else 0
        total_fatalities = int(data_source.get("fatality_count", 0).sum()) if "fatality_count" in data_source.columns else 0
        
        # Find segments where KSI > Total crashes (data inconsistency)
        inconsistencies = []
        if "num_total_crashes" in data_source.columns and "num_ksi_crashes" in data_source.columns:
            inconsistent = data_source[data_source["num_ksi_crashes"] > data_source["num_total_crashes"]]
            inconsistencies = [
                {
                    "id": str(seg.get("segment_id", idx)),
                    "street": str(seg.get("LINEAR_NAME", "Unknown")),
                    "total_crashes": int(seg.get("num_total_crashes", 0)),
                    "ksi_crashes": int(seg.get("num_ksi_crashes", 0)),
                }
                for idx, seg in inconsistent.head(10).iterrows()
            ]
        
        # Sample segments to analyze
        sample_segments = []
        if "num_total_crashes" in data_source.columns:
            # Get segments with high crash counts but low/no KSI
            high_crash_low_ksi = data_source[
                (data_source["num_total_crashes"] >= 20) & 
                (data_source.get("num_ksi_crashes", 0) == 0)
            ].head(5)
            
            sample_segments = [
                {
                    "id": str(seg.get("segment_id", idx)),
                    "street": str(seg.get("LINEAR_NAME", "Unknown")),
                    "total_crashes": int(seg.get("num_total_crashes", 0)),
                    "ksi_crashes": int(seg.get("num_ksi_crashes", 0)) if "num_ksi_crashes" in data_source.columns else 0,
                    "fatalities": int(seg.get("fatality_count", 0)) if "fatality_count" in data_source.columns else 0,
                }
                for idx, seg in high_crash_low_ksi.iterrows()
            ]
        
        return jsonify({
            "summary": {
                "total_segments": total_segments,
                "segments_with_crashes": segments_with_crashes,
                "segments_with_ksi": segments_with_ksi,
                "total_crashes": total_crashes,
                "total_ksi_crashes": total_ksi,
                "total_fatalities": total_fatalities,
                "ksi_ratio": round(total_ksi / total_crashes * 100, 2) if total_crashes > 0 else 0,
            },
            "data_structure_explanation": {
                "total_crashes_source": "Count of records from collision dataset (all traffic collisions)",
                "ksi_crashes_source": "Count of records from KSI dataset (crashes with killed/seriously injured persons)",
                "note": "KSI and collision datasets are counted separately. KSI crashes may overlap with total crashes if they represent the same incidents, or may be separate records. In typical traffic data, KSI crashes are a subset of total crashes.",
            },
            "inconsistencies": {
                "count": len(inconsistencies),
                "examples": inconsistencies,
                "note": "These segments have more KSI crashes than total crashes, which may indicate data issues."
            },
            "sample_high_crash_low_ksi": {
                "count": len(sample_segments),
                "examples": sample_segments,
                "note": "Sample segments with high crash counts but no KSI crashes."
            }
        })
    except Exception as e:
        logging.error(f"Error in data verification: {e}")
        import traceback
        traceback.print_exc()
        return jsonify({"error": str(e)}), 500


@app.route("/api/street-names", methods=["GET"])
def get_street_names():
    """
    Get street name suggestions for autocomplete
    
    Query parameters:
    - query: search query (required, at least 2 characters)
    - limit: maximum number of results (default: 20, max: 100)
    """
    query = request.args.get("query", "").strip()
    
    if len(query) < 2:
        return jsonify({"suggestions": []})
    
    limit = min(int(request.args.get("limit", 20)), 100)
    
    # Use preprocessed_data if available, otherwise fall back to raw road_network
    data_source = preprocessed_data if preprocessed_data is not None else road_network
    
    if data_source is None:
        return jsonify({"suggestions": []})
    
    try:
        # Get unique street names matching the query
        if "LINEAR_NAME" in data_source.columns:
            matching_names = data_source[
                data_source["LINEAR_NAME"].str.contains(query, case=False, na=False)
            ]["LINEAR_NAME"].unique()
            
            # Sort by length (shorter/more exact matches first) then alphabetically
            matching_names = sorted(matching_names, key=lambda x: (len(x), x.lower()))[:limit]
            
            suggestions = [{"name": name, "value": name} for name in matching_names]
            return jsonify({"suggestions": suggestions})
        else:
            return jsonify({"suggestions": []})
    
    except Exception as e:
        logging.error(f"Error in get_street_names: {e}")
        return jsonify({"suggestions": []})


@app.route("/api/segments/all", methods=["GET"])
def get_all_segments():
    """
    Get all segments with optional filtering and pagination
    
    Query parameters:
    - page: page number (default: 1)
    - per_page: items per page (default: 100, max: 1000)
    - search: search in LINEAR_NAME (optional)
    - risk_label: filter by risk label (low/medium/high, optional)
    - min_crashes: minimum total crashes (optional)
    - sort_by: column to sort by (default: id)
    - sort_order: asc or desc (default: asc)
    """
    # Use preprocessed_data if available, otherwise fall back to raw road_network
    data_source = preprocessed_data if preprocessed_data is not None else road_network
    
    if data_source is None:
        return jsonify({"error": "No road data available. Please ensure road network data is loaded."}), 500

    try:
        # Get query parameters
        page = int(request.args.get("page", 1))
        per_page = min(int(request.args.get("per_page", 100)), 1000)
        search = request.args.get("search", "").strip()
        risk_label = request.args.get("risk_label", "").strip().lower()
        min_crashes = request.args.get("min_crashes")
        sort_by = request.args.get("sort_by", "segment_id")
        sort_order = request.args.get("sort_order", "asc").lower()

        # Start with all data
        filtered_data = data_source.copy()

        # Apply search filter
        if search:
            filtered_data = filtered_data[
                filtered_data["LINEAR_NAME"].str.contains(
                    search, case=False, na=False
                )
            ]

        # Apply risk label filter (only if risk_label column exists)
        if risk_label and risk_label in ["low", "medium", "high"]:
            if "risk_label" in filtered_data.columns:
                filtered_data = filtered_data[
                    filtered_data["risk_label"] == risk_label
                ]

        # Apply minimum crashes filter (only if column exists)
        if min_crashes:
            try:
                min_crashes = int(min_crashes)
                if "num_total_crashes" in filtered_data.columns:
                    filtered_data = filtered_data[
                        filtered_data["num_total_crashes"] >= min_crashes
                    ]
            except ValueError:
                pass

        # Prepare data for sorting
        ascending = sort_order == "asc"
        
        # Validate sort column exists
        if sort_by not in filtered_data.columns:
            # If trying to sort by segment_id but it doesn't exist, try to use index
            if sort_by == "segment_id":
                # Sort by index instead
                filtered_data = filtered_data.sort_index(ascending=ascending)
            else:
                # Default to first numeric column or index
                numeric_cols = filtered_data.select_dtypes(include=[np.number]).columns.tolist()
                if numeric_cols:
                    sort_by = numeric_cols[0]
                else:
                    # Fallback to index-based sorting
                    filtered_data = filtered_data.sort_index(ascending=ascending)
                    sort_by = None  # Mark as already sorted

        # Sort data if not already sorted by index
        if sort_by:
            try:
                filtered_data = filtered_data.sort_values(
                    by=sort_by, ascending=ascending, na_position="last"
                )
            except (KeyError, ValueError) as e:
                # Fallback to index sorting if column sorting fails
                logging.warning(f"Could not sort by {sort_by}, using index: {e}")
                filtered_data = filtered_data.sort_index(ascending=ascending)

        # Calculate pagination
        total = len(filtered_data)
        start_idx = (page - 1) * per_page
        end_idx = start_idx + per_page
        paginated_data = filtered_data.iloc[start_idx:end_idx]

        # Convert to JSON-serializable format
        results = []
        for idx, segment in paginated_data.iterrows():
            coords = _extract_coordinates(segment.geometry)

            # Get all relevant columns (handle missing columns gracefully)
            # Calculate segment length from geometry if not available
            segment_length = segment.get("segment_length", 0)
            if pd.isna(segment_length) or segment_length == 0:
                try:
                    if hasattr(segment.geometry, 'length'):
                        segment_length = segment.geometry.length * 111000  # Approximate meters (rough conversion)
                except:
                    segment_length = 0
            
            segment_dict = {
                "id": str(segment.get("segment_id", idx)),
                "LINEAR_NAME": str(segment.get("LINEAR_NAME", "Unknown")),
                "ROAD_CLASS": str(segment.get("ROAD_CLASS", segment.get("LINEAR_NAME_TYPE", "Unknown"))),
                "segment_length": float(segment_length),
                "risk_label": str(segment.get("risk_label", "low")) if "risk_label" in segment else "low",
                "confidence": float(segment.get("confidence", 0.5)) if "confidence" in segment and pd.notna(segment.get("confidence")) else 0.5,
                "num_total_crashes": int(segment.get("num_total_crashes", 0)) if "num_total_crashes" in segment else 0,
                "num_ksi_crashes": int(segment.get("num_ksi_crashes", 0)) if "num_ksi_crashes" in segment else 0,
                "fatality_count": int(segment.get("fatality_count", 0)) if "fatality_count" in segment else 0,
                "ksi_ratio": float(segment.get("ksi_ratio", 0)) if "ksi_ratio" in segment else 0.0,
                "crash_density": float(segment.get("crash_density", 0)) if "crash_density" in segment else 0.0,
                "coordinates": coords,
            }
            results.append(segment_dict)

        return jsonify(
            {
                "data": results,
                "pagination": {
                    "page": page,
                    "per_page": per_page,
                    "total": total,
                    "total_pages": (total + per_page - 1) // per_page,
                },
            }
        )

    except Exception as e:
        logging.error(f"Error in get_all_segments: {e}")
        import traceback

        traceback.print_exc()
        return jsonify({"error": str(e)}), 500


def _get_data_validation_html():
    """Return HTML template for data validation page"""
    return """
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Street Segment Data Validation</title>
    <style>
        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }
        
        body {
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, sans-serif;
            background: #f5f5f7;
            color: #1d1d1f;
            padding: 20px;
        }
        
        .container {
            max-width: 1400px;
            margin: 0 auto;
            background: white;
            border-radius: 12px;
            box-shadow: 0 2px 10px rgba(0,0,0,0.1);
            padding: 30px;
        }
        
        h1 {
            font-size: 32px;
            margin-bottom: 10px;
            color: #1d1d1f;
        }
        
        .subtitle {
            color: #86868b;
            margin-bottom: 30px;
            font-size: 14px;
        }
        
        .controls {
            display: flex;
            gap: 15px;
            flex-wrap: wrap;
            margin-bottom: 25px;
            padding: 20px;
            background: #f5f5f7;
            border-radius: 8px;
        }
        
        .control-group {
            display: flex;
            flex-direction: column;
            gap: 5px;
        }
        
        .control-group label {
            font-size: 12px;
            font-weight: 600;
            color: #6e6e73;
            text-transform: uppercase;
            letter-spacing: 0.5px;
        }
        
        input, select {
            padding: 8px 12px;
            border: 1px solid #d2d2d7;
            border-radius: 6px;
            font-size: 14px;
            transition: all 0.2s;
        }
        
        input:focus, select:focus {
            outline: none;
            border-color: #0071e3;
            box-shadow: 0 0 0 3px rgba(0,113,227,0.1);
        }
        
        .search-input {
            min-width: 250px;
        }
        
        .autocomplete-container {
            position: relative;
            width: 100%;
        }
        
        .autocomplete-dropdown {
            position: absolute;
            top: 100%;
            left: 0;
            right: 0;
            background: white;
            border: 1px solid #d2d2d7;
            border-top: none;
            border-radius: 0 0 6px 6px;
            max-height: 200px;
            overflow-y: auto;
            z-index: 1000;
            box-shadow: 0 4px 12px rgba(0,0,0,0.1);
            display: none;
        }
        
        .autocomplete-dropdown.show {
            display: block;
        }
        
        .autocomplete-item {
            padding: 10px 12px;
            cursor: pointer;
            border-bottom: 1px solid #f5f5f7;
            transition: background 0.15s;
        }
        
        .autocomplete-item:hover,
        .autocomplete-item.selected {
            background: #f5f5f7;
        }
        
        .autocomplete-item:last-child {
            border-bottom: none;
        }
        
        .autocomplete-item strong {
            color: #0071e3;
        }
        
        .stats {
            display: flex;
            gap: 20px;
            margin-bottom: 25px;
            flex-wrap: wrap;
        }
        
        .stat-card {
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            color: white;
            padding: 20px;
            border-radius: 8px;
            min-width: 150px;
        }
        
        .stat-card.high-risk {
            background: linear-gradient(135deg, #f093fb 0%, #f5576c 100%);
        }
        
        .stat-card.medium-risk {
            background: linear-gradient(135deg, #fa709a 0%, #fee140 100%);
        }
        
        .stat-card.low-risk {
            background: linear-gradient(135deg, #30cfd0 0%, #330867 100%);
        }
        
        .stat-label {
            font-size: 12px;
            opacity: 0.9;
            text-transform: uppercase;
            letter-spacing: 0.5px;
        }
        
        .stat-value {
            font-size: 28px;
            font-weight: 600;
            margin-top: 5px;
        }
        
        .table-container {
            overflow-x: auto;
            border-radius: 8px;
            border: 1px solid #d2d2d7;
        }
        
        table {
            width: 100%;
            border-collapse: collapse;
            font-size: 13px;
        }
        
        thead {
            background: #f5f5f7;
            position: sticky;
            top: 0;
        }
        
        th {
            padding: 12px 15px;
            text-align: left;
            font-weight: 600;
            color: #6e6e73;
            text-transform: uppercase;
            font-size: 11px;
            letter-spacing: 0.5px;
            border-bottom: 2px solid #d2d2d7;
            cursor: pointer;
            user-select: none;
        }
        
        th:hover {
            background: #e8e8ed;
        }
        
        th.sorted {
            color: #0071e3;
        }
        
        td {
            padding: 12px 15px;
            border-bottom: 1px solid #e8e8ed;
        }
        
        tbody tr:hover {
            background: #f9f9fb;
        }
        
        tbody tr:last-child td {
            border-bottom: none;
        }
        
        .risk-badge {
            display: inline-block;
            padding: 4px 12px;
            border-radius: 12px;
            font-size: 11px;
            font-weight: 600;
            text-transform: uppercase;
        }
        
        .risk-high {
            background: #ff3b30;
            color: white;
        }
        
        .risk-medium {
            background: #ff9500;
            color: white;
        }
        
        .risk-low {
            background: #34c759;
            color: white;
        }
        
        .pagination {
            display: flex;
            justify-content: space-between;
            align-items: center;
            margin-top: 20px;
            padding: 15px;
            background: #f5f5f7;
            border-radius: 8px;
        }
        
        .pagination-info {
            color: #6e6e73;
            font-size: 14px;
        }
        
        .pagination-controls {
            display: flex;
            gap: 10px;
        }
        
        button {
            padding: 8px 16px;
            background: #0071e3;
            color: white;
            border: none;
            border-radius: 6px;
            cursor: pointer;
            font-size: 14px;
            font-weight: 500;
            transition: all 0.2s;
        }
        
        button:hover:not(:disabled) {
            background: #0077ed;
            transform: translateY(-1px);
            box-shadow: 0 2px 8px rgba(0,113,227,0.3);
        }
        
        button:disabled {
            background: #d2d2d7;
            cursor: not-allowed;
            opacity: 0.6;
        }
        
        .loading {
            text-align: center;
            padding: 40px;
            color: #6e6e73;
        }
        
        .error {
            background: #ff3b30;
            color: white;
            padding: 15px;
            border-radius: 8px;
            margin-bottom: 20px;
        }
        
        .num-cell {
            text-align: right;
            font-variant-numeric: tabular-nums;
        }
        
        .coordinates-info {
            font-size: 11px;
            color: #6e6e73;
        }
    </style>
</head>
<body>
    <div class="container">
        <h1>Street Segment Data Validation</h1>
        <p class="subtitle">Review all street segments and their associated risk data for accuracy</p>
        
        <div class="controls">
            <div class="control-group">
                <label>Search Street Name</label>
                <div class="autocomplete-container">
                    <input type="text" id="searchInput" class="search-input" placeholder="Enter street name..." autocomplete="off">
                    <div class="autocomplete-dropdown" id="autocompleteDropdown"></div>
                </div>
            </div>
            
            <div class="control-group">
                <label>Risk Level</label>
                <select id="riskFilter">
                    <option value="">All Risk Levels</option>
                    <option value="high">High Risk</option>
                    <option value="medium">Medium Risk</option>
                    <option value="low">Low Risk</option>
                </select>
            </div>
            
            <div class="control-group">
                <label>Min Crashes</label>
                <input type="number" id="minCrashes" placeholder="0" min="0">
            </div>
            
            <div class="control-group">
                <label>Sort By</label>
                <select id="sortBy">
                    <option value="segment_id">ID</option>
                    <option value="LINEAR_NAME">Street Name</option>
                    <option value="risk_label">Risk Level</option>
                    <option value="num_total_crashes">Total Crashes</option>
                    <option value="confidence">Confidence</option>
                    <option value="segment_length">Length</option>
                </select>
            </div>
            
            <div class="control-group">
                <label>Order</label>
                <select id="sortOrder">
                    <option value="asc">Ascending</option>
                    <option value="desc">Descending</option>
                </select>
            </div>
            
            <div class="control-group">
                <label>Per Page</label>
                <select id="perPage">
                    <option value="50">50</option>
                    <option value="100" selected>100</option>
                    <option value="250">250</option>
                    <option value="500">500</option>
                    <option value="1000">1000</option>
                </select>
            </div>
        </div>
        
        <div class="stats" id="stats">
            <!-- Stats will be populated dynamically -->
        </div>
        
        <div style="background: #fff3cd; border: 1px solid #ffc107; border-radius: 8px; padding: 15px; margin-bottom: 20px;">
            <h3 style="margin-top: 0; color: #856404;">📊 Data Verification Note</h3>
            <p style="margin-bottom: 10px; color: #856404;">
                <strong>Understanding the crash data structure:</strong>
            </p>
            <ul style="margin-bottom: 10px; color: #856404; padding-left: 20px;">
                <li><strong>Total Crashes:</strong> Count of all records from the collision dataset</li>
                <li><strong>KSI Crashes:</strong> Count of all records from the KSI (Killed/Seriously Injured) dataset</li>
                <li><strong>Fatalities:</strong> Count of fatalities from both datasets</li>
            </ul>
            <p style="margin-bottom: 10px; color: #856404;">
                <strong>Important:</strong> The collision and KSI datasets are counted separately. KSI crashes may:
            </p>
            <ul style="margin-bottom: 10px; color: #856404; padding-left: 20px;">
                <li>Be a subset of total crashes (if KSI records are also in the collision dataset)</li>
                <li>Be separate records (if KSI dataset contains different crashes)</li>
            </ul>
            <p style="margin-bottom: 0;">
                <button onclick="showDataVerification()" style="background: #856404; color: white; border: none; padding: 8px 16px; border-radius: 4px; cursor: pointer; margin-right: 10px;">
                    View Data Verification Details
                </button>
                <button onclick="showFatalityDiagnostic()" style="background: #dc3545; color: white; border: none; padding: 8px 16px; border-radius: 4px; cursor: pointer;">
                    🔍 Diagnose Fatality Data Issue
                </button>
            </p>
            <div id="verificationDetails" style="display: none; margin-top: 15px; padding: 10px; background: white; border-radius: 4px;"></div>
            <div id="fatalityDiagnosticDetails" style="display: none; margin-top: 15px; padding: 10px; background: white; border-radius: 4px;"></div>
        </div>
        
        <div id="errorContainer"></div>
        <div id="loadingMessage" class="loading">Loading data...</div>
        
        <div class="table-container" id="tableContainer" style="display: none;">
            <table>
                <thead>
                    <tr>
                        <th data-sort="segment_id">ID</th>
                        <th data-sort="LINEAR_NAME">Street Name</th>
                        <th data-sort="ROAD_CLASS">Road Class</th>
                        <th data-sort="segment_length">Length (m)</th>
                        <th data-sort="risk_label">Risk</th>
                        <th data-sort="confidence">Confidence</th>
                        <th data-sort="num_total_crashes">Total Crashes</th>
                        <th data-sort="num_ksi_crashes">KSI Crashes</th>
                        <th data-sort="fatality_count">Fatalities</th>
                        <th data-sort="crash_density">Crash Density</th>
                        <th>Coordinates</th>
                    </tr>
                </thead>
                <tbody id="tableBody">
                    <!-- Table rows will be populated dynamically -->
                </tbody>
            </table>
        </div>
        
        <div class="pagination" id="pagination" style="display: none;">
            <div class="pagination-info" id="paginationInfo"></div>
            <div class="pagination-controls">
                <button id="prevPage" disabled>Previous</button>
                <button id="nextPage" disabled>Next</button>
            </div>
        </div>
    </div>
    
    <script>
        let currentPage = 1;
        let currentFilters = {};
        let autocompleteTimeout = null;
        let selectedAutocompleteIndex = -1;
        
        // Initialize
        document.addEventListener('DOMContentLoaded', () => {
            setupEventListeners();
            loadData();
        });
        
        function setupEventListeners() {
            const searchInput = document.getElementById('searchInput');
            
            // Autocomplete on input
            searchInput.addEventListener('input', (e) => {
                const query = e.target.value.trim();
                if (query.length >= 2) {
                    clearTimeout(autocompleteTimeout);
                    autocompleteTimeout = setTimeout(() => {
                        fetchAutocompleteSuggestions(query);
                    }, 300);
                } else {
                    hideAutocomplete();
                }
                handleFilterChange();
            });
            
            // Keyboard navigation for autocomplete
            searchInput.addEventListener('keydown', (e) => {
                const dropdown = document.getElementById('autocompleteDropdown');
                const items = dropdown.querySelectorAll('.autocomplete-item');
                
                if (e.key === 'ArrowDown') {
                    e.preventDefault();
                    selectedAutocompleteIndex = Math.min(selectedAutocompleteIndex + 1, items.length - 1);
                    updateAutocompleteSelection(items);
                } else if (e.key === 'ArrowUp') {
                    e.preventDefault();
                    selectedAutocompleteIndex = Math.max(selectedAutocompleteIndex - 1, -1);
                    updateAutocompleteSelection(items);
                } else if (e.key === 'Enter' && selectedAutocompleteIndex >= 0) {
                    e.preventDefault();
                    if (items[selectedAutocompleteIndex]) {
                        items[selectedAutocompleteIndex].click();
                    }
                } else if (e.key === 'Escape') {
                    hideAutocomplete();
                }
            });
            
            // Hide autocomplete when clicking outside
            document.addEventListener('click', (e) => {
                if (!e.target.closest('.autocomplete-container')) {
                    hideAutocomplete();
                }
            });
            
            document.getElementById('riskFilter').addEventListener('change', handleFilterChange);
            document.getElementById('minCrashes').addEventListener('input', debounce(handleFilterChange, 500));
            document.getElementById('sortBy').addEventListener('change', handleFilterChange);
            document.getElementById('sortOrder').addEventListener('change', handleFilterChange);
            document.getElementById('perPage').addEventListener('change', () => {
                currentPage = 1;
                handleFilterChange();
            });
            
            document.getElementById('prevPage').addEventListener('click', () => {
                if (currentPage > 1) {
                    currentPage--;
                    loadData();
                }
            });
            
            document.getElementById('nextPage').addEventListener('click', () => {
                currentPage++;
                loadData();
            });
            
            // Table header sorting
            document.querySelectorAll('th[data-sort]').forEach(th => {
                th.addEventListener('click', () => {
                    const sortBy = th.getAttribute('data-sort');
                    const currentSortBy = document.getElementById('sortBy').value;
                    const currentOrder = document.getElementById('sortOrder').value;
                    
                    if (currentSortBy === sortBy) {
                        document.getElementById('sortOrder').value = currentOrder === 'asc' ? 'desc' : 'asc';
                    } else {
                        document.getElementById('sortBy').value = sortBy;
                        document.getElementById('sortOrder').value = 'asc';
                    }
                    
                    handleFilterChange();
                });
            });
        }
        
        function handleFilterChange() {
            currentPage = 1;
            loadData();
        }
        
        async function fetchAutocompleteSuggestions(query) {
            try {
                const response = await fetch(`/api/street-names?query=${encodeURIComponent(query)}&limit=20`);
                const result = await response.json();
                displayAutocompleteSuggestions(result.suggestions || [], query);
            } catch (error) {
                console.error('Error fetching autocomplete suggestions:', error);
                hideAutocomplete();
            }
        }
        
        function displayAutocompleteSuggestions(suggestions, query) {
            const dropdown = document.getElementById('autocompleteDropdown');
            dropdown.innerHTML = '';
            selectedAutocompleteIndex = -1;
            
            if (suggestions.length === 0) {
                hideAutocomplete();
                return;
            }
            
            suggestions.forEach((suggestion, index) => {
                const item = document.createElement('div');
                item.className = 'autocomplete-item';
                
                // Highlight matching part
                const name = suggestion.name;
                const queryLower = query.toLowerCase();
                const nameLower = name.toLowerCase();
                const matchIndex = nameLower.indexOf(queryLower);
                
                if (matchIndex >= 0) {
                    const beforeMatch = name.substring(0, matchIndex);
                    const match = name.substring(matchIndex, matchIndex + query.length);
                    const afterMatch = name.substring(matchIndex + query.length);
                    item.innerHTML = `${beforeMatch}<strong>${match}</strong>${afterMatch}`;
                } else {
                    item.textContent = name;
                }
                
                item.addEventListener('click', () => {
                    document.getElementById('searchInput').value = name;
                    hideAutocomplete();
                    handleFilterChange();
                });
                
                dropdown.appendChild(item);
            });
            
            dropdown.classList.add('show');
        }
        
        function updateAutocompleteSelection(items) {
            items.forEach((item, index) => {
                if (index === selectedAutocompleteIndex) {
                    item.classList.add('selected');
                    item.scrollIntoView({ block: 'nearest' });
                } else {
                    item.classList.remove('selected');
                }
            });
        }
        
        function hideAutocomplete() {
            const dropdown = document.getElementById('autocompleteDropdown');
            dropdown.classList.remove('show');
            selectedAutocompleteIndex = -1;
        }
        
        function debounce(func, wait) {
            let timeout;
            return function executedFunction(...args) {
                const later = () => {
                    clearTimeout(timeout);
                    func(...args);
                };
                clearTimeout(timeout);
                timeout = setTimeout(later, wait);
            };
        }
        
        async function loadData() {
            const search = document.getElementById('searchInput').value;
            const riskLabel = document.getElementById('riskFilter').value;
            const minCrashes = document.getElementById('minCrashes').value;
            const sortBy = document.getElementById('sortBy').value;
            const sortOrder = document.getElementById('sortOrder').value;
            const perPage = document.getElementById('perPage').value;
            
            const params = new URLSearchParams({
                page: currentPage,
                per_page: perPage,
                sort_by: sortBy,
                sort_order: sortOrder
            });
            
            if (search) params.append('search', search);
            if (riskLabel) params.append('risk_label', riskLabel);
            if (minCrashes) params.append('min_crashes', minCrashes);
            
            document.getElementById('loadingMessage').style.display = 'block';
            document.getElementById('tableContainer').style.display = 'none';
            document.getElementById('pagination').style.display = 'none';
            document.getElementById('errorContainer').innerHTML = '';
            
            try {
                const response = await fetch(`/api/segments/all?${params}`);
                const result = await response.json();
                
                if (!response.ok) {
                    throw new Error(result.error || 'Failed to load data');
                }
                
                displayData(result);
                updateStats(result);
                updatePagination(result.pagination);
                
            } catch (error) {
                document.getElementById('errorContainer').innerHTML = 
                    `<div class="error">Error: ${error.message}</div>`;
            } finally {
                document.getElementById('loadingMessage').style.display = 'none';
            }
        }
        
        function displayData(result) {
            const tbody = document.getElementById('tableBody');
            tbody.innerHTML = '';
            
            if (result.data.length === 0) {
                tbody.innerHTML = '<tr><td colspan="11" style="text-align: center; padding: 40px; color: #6e6e73;">No segments found matching your filters</td></tr>';
                document.getElementById('tableContainer').style.display = 'block';
                return;
            }
            
            result.data.forEach(segment => {
                const row = document.createElement('tr');
                row.innerHTML = `
                    <td>${segment.id}</td>
                    <td>${segment.LINEAR_NAME}</td>
                    <td>${segment.ROAD_CLASS}</td>
                    <td class="num-cell">${segment.segment_length.toFixed(2)}</td>
                    <td><span class="risk-badge risk-${segment.risk_label}">${segment.risk_label}</span></td>
                    <td class="num-cell">${(segment.confidence * 100).toFixed(1)}%</td>
                    <td class="num-cell">${segment.num_total_crashes}</td>
                    <td class="num-cell">${segment.num_ksi_crashes}</td>
                    <td class="num-cell">${segment.fatality_count}</td>
                    <td class="num-cell">${segment.crash_density.toFixed(4)}</td>
                    <td class="coordinates-info">${segment.coordinates.length} points</td>
                `;
                tbody.appendChild(row);
            });
            
            document.getElementById('tableContainer').style.display = 'block';
            
            // Update sorted column indicator
            const sortBy = document.getElementById('sortBy').value;
            document.querySelectorAll('th').forEach(th => {
                th.classList.remove('sorted');
                if (th.getAttribute('data-sort') === sortBy) {
                    th.classList.add('sorted');
                }
            });
        }
        
        function updateStats(result) {
            const statsContainer = document.getElementById('stats');
            const riskCounts = { high: 0, medium: 0, low: 0 };
            let totalCrashes = 0;
            
            result.data.forEach(segment => {
                riskCounts[segment.risk_label]++;
                totalCrashes += segment.num_total_crashes;
            });
            
            // If we have pagination info, show filtered stats
            // For now, we'll just show current page stats
            statsContainer.innerHTML = `
                <div class="stat-card">
                    <div class="stat-label">Segments Shown</div>
                    <div class="stat-value">${result.data.length}</div>
                </div>
                <div class="stat-card high-risk">
                    <div class="stat-label">High Risk</div>
                    <div class="stat-value">${riskCounts.high}</div>
                </div>
                <div class="stat-card medium-risk">
                    <div class="stat-label">Medium Risk</div>
                    <div class="stat-value">${riskCounts.medium}</div>
                </div>
                <div class="stat-card low-risk">
                    <div class="stat-label">Low Risk</div>
                    <div class="stat-value">${riskCounts.low}</div>
                </div>
                <div class="stat-card">
                    <div class="stat-label">Total Crashes</div>
                    <div class="stat-value">${totalCrashes}</div>
                </div>
            `;
        }
        
        function updatePagination(pagination) {
            document.getElementById('paginationInfo').textContent = 
                `Showing ${((pagination.page - 1) * pagination.per_page) + 1} - ${Math.min(pagination.page * pagination.per_page, pagination.total)} of ${pagination.total} segments`;
            
            document.getElementById('prevPage').disabled = pagination.page === 1;
            document.getElementById('nextPage').disabled = pagination.page >= pagination.total_pages;
            
            document.getElementById('pagination').style.display = 'flex';
        }
        
        async function showDataVerification() {
            const detailsDiv = document.getElementById('verificationDetails');
            detailsDiv.style.display = 'block';
            detailsDiv.innerHTML = '<p>Loading verification data...</p>';
            
            try {
                const response = await fetch('/api/data-verification');
                const result = await response.json();
                
                if (!response.ok) {
                    throw new Error(result.error || 'Failed to load verification data');
                }
                
                let html = '<h4 style="margin-top: 0;">Data Summary</h4>';
                html += `<table style="width: 100%; border-collapse: collapse; margin-bottom: 15px;">`;
                html += `<tr><td style="padding: 5px;"><strong>Total Segments:</strong></td><td style="padding: 5px;">${result.summary.total_segments.toLocaleString()}</td></tr>`;
                html += `<tr><td style="padding: 5px;"><strong>Total Crashes:</strong></td><td style="padding: 5px;">${result.summary.total_crashes.toLocaleString()}</td></tr>`;
                html += `<tr><td style="padding: 5px;"><strong>Total KSI Crashes:</strong></td><td style="padding: 5px;">${result.summary.total_ksi_crashes.toLocaleString()}</td></tr>`;
                html += `<tr><td style="padding: 5px;"><strong>KSI Ratio:</strong></td><td style="padding: 5px;">${result.summary.ksi_ratio}%</td></tr>`;
                html += `<tr><td style="padding: 5px;"><strong>Total Fatalities:</strong></td><td style="padding: 5px;">${result.summary.total_fatalities.toLocaleString()}</td></tr>`;
                html += `</table>`;
                
                html += `<h4>Data Structure Explanation</h4>`;
                html += `<p><strong>Total Crashes Source:</strong> ${result.data_structure_explanation.total_crashes_source}</p>`;
                html += `<p><strong>KSI Crashes Source:</strong> ${result.data_structure_explanation.ksi_crashes_source}</p>`;
                html += `<p><em>${result.data_structure_explanation.note}</em></p>`;
                
                if (result.inconsistencies.count > 0) {
                    html += `<h4 style="color: #dc3545;">⚠️ Data Inconsistencies Found (${result.inconsistencies.count})</h4>`;
                    html += `<p><em>${result.inconsistencies.note}</em></p>`;
                    html += `<ul>`;
                    result.inconsistencies.examples.forEach(seg => {
                        html += `<li><strong>${seg.street}</strong> (ID: ${seg.id}): ${seg.ksi_crashes} KSI crashes but only ${seg.total_crashes} total crashes</li>`;
                    });
                    html += `</ul>`;
                }
                
                if (result.sample_high_crash_low_ksi.count > 0) {
                    html += `<h4>Sample Segments: High Crashes, Low/No KSI</h4>`;
                    html += `<p><em>${result.sample_high_crash_low_ksi.note}</em></p>`;
                    html += `<table style="width: 100%; border-collapse: collapse; font-size: 12px;">`;
                    html += `<tr style="background: #f5f5f7;"><th style="padding: 8px; text-align: left;">Street</th><th style="padding: 8px;">Total Crashes</th><th style="padding: 8px;">KSI Crashes</th><th style="padding: 8px;">Fatalities</th></tr>`;
                    result.sample_high_crash_low_ksi.examples.forEach(seg => {
                        html += `<tr><td style="padding: 8px;">${seg.street}</td><td style="padding: 8px; text-align: center;">${seg.total_crashes}</td><td style="padding: 8px; text-align: center;">${seg.ksi_crashes}</td><td style="padding: 8px; text-align: center;">${seg.fatalities}</td></tr>`;
                    });
                    html += `</table>`;
                }
                
                detailsDiv.innerHTML = html;
            } catch (error) {
                detailsDiv.innerHTML = `<p style="color: #dc3545;">Error loading verification data: ${error.message}</p>`;
            }
        }
        
        async function showFatalityDiagnostic() {
            const detailsDiv = document.getElementById('fatalityDiagnosticDetails');
            detailsDiv.style.display = 'block';
            detailsDiv.innerHTML = '<p>Analyzing fatality data structure...</p>';
            
            try {
                const response = await fetch('/api/fatality-diagnostic');
                const result = await response.json();
                
                if (!response.ok) {
                    throw new Error(result.error || 'Failed to load diagnostic data');
                }
                
                let html = '<h4 style="margin-top: 0;">🔍 Fatality Data Diagnostic</h4>';
                
                if (result.error) {
                    html += `<p style="color: #dc3545;"><strong>Error:</strong> ${result.error}</p>`;
                    if (result.traceback) {
                        html += `<pre style="background: #f5f5f5; padding: 10px; border-radius: 4px; overflow-x: auto; font-size: 11px;">${result.traceback}</pre>`;
                    }
                } else {
                    // Collision data info
                    html += '<h5>📊 Collision Dataset</h5>';
                    if (result.collision_data.error) {
                        html += `<p style="color: #dc3545;">Error: ${result.collision_data.error}</p>`;
                    } else {
                        html += `<ul>`;
                        html += `<li><strong>Total Records:</strong> ${result.collision_data.total_records?.toLocaleString() || 'N/A'}</li>`;
                        html += `<li><strong>Expected Fatalities Column:</strong> <code>${result.collision_data.fatalities_column}</code></li>`;
                        html += `<li><strong>Column Exists:</strong> ${result.collision_data.has_fatalities_col ? '✅ Yes' : '❌ No'}</li>`;
                        html += `<li><strong>Expected Injury Column:</strong> <code>${result.collision_data.injury_column}</code></li>`;
                        html += `<li><strong>Column Exists:</strong> ${result.collision_data.has_injury_col ? '✅ Yes' : '❌ No'}</li>`;
                        if (result.collision_data.fatalities_column_stats) {
                            html += `<li><strong>Non-Zero Fatalities:</strong> ${result.collision_data.non_zero_fatalities_count || 0}</li>`;
                            html += `<li><strong>Unique Values in Fatalities Column:</strong> ${Object.keys(result.collision_data.fatalities_column_stats.unique_values || {}).length}</li>`;
                        }
                        if (result.collision_data.fatal_in_injury_count !== undefined) {
                            html += `<li><strong>Records with "Fatal" in Injury Column:</strong> ${result.collision_data.fatal_in_injury_count}</li>`;
                        }
                        html += `</ul>`;
                        
                        if (result.collision_data.fatalities_column_stats) {
                            html += `<details style="margin-top: 10px;"><summary>Sample Fatalities Column Values</summary>`;
                            html += `<pre style="background: #f5f5f5; padding: 10px; border-radius: 4px; overflow-x: auto; font-size: 11px;">${JSON.stringify(result.collision_data.fatalities_column_stats, null, 2)}</pre>`;
                            html += `</details>`;
                        }
                    }
                    
                    // KSI data info
                    html += '<h5 style="margin-top: 20px;">🚨 KSI Dataset</h5>';
                    if (result.ksi_data.error) {
                        html += `<p style="color: #dc3545;">Error: ${result.ksi_data.error}</p>`;
                    } else {
                        html += `<ul>`;
                        html += `<li><strong>Total Records:</strong> ${result.ksi_data.total_records?.toLocaleString() || 'N/A'}</li>`;
                        html += `<li><strong>Expected Fatalities Column:</strong> <code>${result.ksi_data.fatalities_column}</code></li>`;
                        html += `<li><strong>Column Exists:</strong> ${result.ksi_data.has_fatalities_col ? '✅ Yes' : '❌ No'}</li>`;
                        html += `<li><strong>Expected Injury Column:</strong> <code>${result.ksi_data.injury_column}</code></li>`;
                        html += `<li><strong>Column Exists:</strong> ${result.ksi_data.has_injury_col ? '✅ Yes' : '❌ No'}</li>`;
                        if (result.ksi_data.fatalities_column_stats) {
                            html += `<li><strong>Non-Zero Fatalities:</strong> ${result.ksi_data.non_zero_fatalities_count || 0}</li>`;
                            html += `<li><strong>Data Type:</strong> ${result.ksi_data.fatalities_column_stats.data_type || 'N/A'}</li>`;
                        }
                        if (result.ksi_data.fatal_in_injury_count !== undefined) {
                            html += `<li><strong>Records with "Fatal" in Injury Column:</strong> ${result.ksi_data.fatal_in_injury_count}</li>`;
                        }
                        html += `</ul>`;
                        
                        if (result.ksi_data.fatalities_column_stats) {
                            html += `<details style="margin-top: 10px;"><summary>Sample Fatalities Column Values</summary>`;
                            html += `<pre style="background: #f5f5f5; padding: 10px; border-radius: 4px; overflow-x: auto; font-size: 11px;">${JSON.stringify(result.ksi_data.fatalities_column_stats, null, 2)}</pre>`;
                            html += `</details>`;
                        }
                    }
                    
                    // All available columns
                    if (result.collision_data.columns) {
                        html += `<details style="margin-top: 15px;"><summary>All Columns in Collision Dataset</summary>`;
                        html += `<p style="font-size: 12px;">${result.collision_data.columns.join(', ')}</p>`;
                        html += `</details>`;
                    }
                    if (result.ksi_data.columns) {
                        html += `<details style="margin-top: 10px;"><summary>All Columns in KSI Dataset</summary>`;
                        html += `<p style="font-size: 12px;">${result.ksi_data.columns.join(', ')}</p>`;
                        html += `</details>`;
                    }
                }
                
                detailsDiv.innerHTML = html;
            } catch (error) {
                detailsDiv.innerHTML = `<p style="color: #dc3545;">Error loading diagnostic data: ${error.message}</p>`;
            }
        }
    </script>
</body>
</html>
    """


if __name__ == "__main__":
    logging.basicConfig(level=logging.INFO)
    app.run(host="0.0.0.0", port=8000, debug=True, use_reloader=False)
