"""
flask API server
serves risk predictions from the trained model
"""

from flask import Flask, request, jsonify, Response
from flask_cors import CORS
import numpy as np
import pandas as pd
import geopandas as gpd
from pathlib import Path
import logging
import sys
from shapely.geometry import Point, box
from sklearn.neighbors import BallTree

# import existing modules
PROJECT_ROOT = Path(__file__).parent.parent
sys.path.insert(0, str(PROJECT_ROOT))

# import existing modules
from src.models.model_trainer import ModelTrainer
from src.data_processing.data_loader import load_road_network
from src.data_processing.spatial_join_fast import perform_spatial_join_fast
from src.feature_engineering.feature_creator import create_segment_features
from src.feature_engineering.label_generator import generate_risk_labels

app = Flask(__name__)
CORS(app)

# initialize model trainer and load model
MODEL_PATH = PROJECT_ROOT / "outputs" / "models" / "toronto_risk_model.joblib"
model_trainer = ModelTrainer()

try:
    model_trainer.load_model(str(MODEL_PATH))
    logging.info("Model loaded successfully")
except Exception as e:
    logging.error(f"Failed to load model: {e}")
    model_trainer = None

# load pre-processed road network with predictions
# this should be generated by running the full pipeline once
PREPROCESSED_DATA_PATH = (
    PROJECT_ROOT / "outputs" / "reports" / "toronto_road_risk.geojson"
)
preprocessed_data = None

try:
    if PREPROCESSED_DATA_PATH.exists():
        preprocessed_data = gpd.read_file(PREPROCESSED_DATA_PATH)
        logging.info(f"Loaded {len(preprocessed_data)} pre-processed road segments")
    else:
        logging.warning(
            "Pre-processed data not found. Will process on-demand (slower)."
        )
except Exception as e:
    logging.warning(f"Could not load pre-processed data: {e}")

# Load raw road network for on-demand processing
road_network = None
try:
    data_dir = PROJECT_ROOT / "data"
    road_network = load_road_network(data_dir)
    logging.info(f"Loaded {len(road_network)} road segments")
except Exception as e:
    logging.warning(f"Could not load road network: {e}")


@app.route("/", methods=["GET"])
def root():
    """Landing page with API info and viewer options"""
    return Response("""
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Risk Map Model API</title>
    <style>
        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }
        
        body {
            font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            min-height: 100vh;
            padding: 40px 20px;
            display: flex;
            justify-content: center;
            align-items: center;
        }
        
        .container {
            max-width: 800px;
            width: 100%;
            background: white;
            border-radius: 20px;
            padding: 40px;
            box-shadow: 0 20px 60px rgba(0,0,0,0.3);
        }
        
        h1 {
            color: #333;
            margin-bottom: 10px;
            font-size: 2.5em;
        }
        
        .subtitle {
            color: #666;
            margin-bottom: 30px;
            font-size: 1.1em;
        }
        
        .options {
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(250px, 1fr));
            gap: 20px;
            margin: 40px 0;
        }
        
        .option-card {
            border: 2px solid #e0e0e0;
            border-radius: 12px;
            padding: 30px;
            text-align: center;
            transition: all 0.3s;
            cursor: pointer;
            text-decoration: none;
            color: inherit;
        }
        
        .option-card:hover {
            border-color: #007AFF;
            transform: translateY(-5px);
            box-shadow: 0 10px 30px rgba(0,122,255,0.2);
        }
        
        .option-card h2 {
            color: #007AFF;
            margin-bottom: 10px;
            font-size: 1.5em;
        }
        
        .option-card p {
            color: #666;
            line-height: 1.6;
        }
        
        .icon {
            font-size: 3em;
            margin-bottom: 15px;
        }
        
        .api-info {
            background: #f8f9fa;
            border-radius: 12px;
            padding: 25px;
            margin-top: 30px;
        }
        
        .api-info h3 {
            color: #333;
            margin-bottom: 15px;
        }
        
        .endpoint {
            background: white;
            padding: 10px 15px;
            border-radius: 8px;
            margin: 8px 0;
            font-family: 'Courier New', monospace;
            font-size: 0.9em;
            color: #333;
            border-left: 4px solid #007AFF;
        }
        
        .badge {
            display: inline-block;
            background: #007AFF;
            color: white;
            padding: 4px 12px;
            border-radius: 12px;
            font-size: 0.8em;
            font-weight: 600;
            margin-left: 10px;
        }
    </style>
</head>
<body>
    <div class="container">
        <h1>Risk Map Model API</h1>
        <p class="subtitle">Road crash risk prediction API for Toronto</p>
        
        <div class="options">
            <a href="/web" class="option-card">
                <div class="icon">🌐</div>
                <h2>Web Viewer</h2>
                <p>View the risk map in your web browser. Perfect for Windows users and quick testing.</p>
            </a>
            
            <a href="/api/health" class="option-card">
                <div class="icon">📱</div>
                <h2>iOS App</h2>
                <p>For iOS development. Connect your iOS app to these API endpoints.</p>
            </a>
        </div>
        
        <div class="api-info">
            <h3>API Endpoints</h3>
            <div class="endpoint">GET <code>/api/health</code> <span class="badge">Health Check</span></div>
            <div class="endpoint">POST <code>/api/risk-predictions</code> <span class="badge">Get predictions for region</span></div>
            <div class="endpoint">POST <code>/api/risk-prediction</code> <span class="badge">Get prediction for location</span></div>
        </div>
    </div>
</body>
</html>
""", mimetype='text/html')


@app.route("/web", methods=["GET"])
def web_demo():
    """Web demo interface mimicking iOS app - for Windows browser testing"""
    return Response("""
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
    <title>Risk Map - Toronto</title>
    <link rel="stylesheet" href="https://unpkg.com/leaflet@1.9.4/dist/leaflet.css" />
    <script src="https://unpkg.com/leaflet@1.9.4/dist/leaflet.js"></script>
    <style>
        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }
        
        body {
            font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
            overflow: hidden;
            height: 100vh;
            background: #000;
        }
        
        #map-container {
            width: 100%;
            height: 100vh;
            position: relative;
        }
        
        #map {
            width: 100%;
            height: 100%;
        }
        
        .error-banner {
            position: absolute;
            top: 50%;
            left: 50%;
            transform: translate(-50%, -50%);
            background: #DC143C;
            color: white;
            padding: 16px 24px;
            border-radius: 12px;
            z-index: 1000;
            text-align: center;
            box-shadow: 0 4px 12px rgba(0,0,0,0.3);
            display: none;
        }
        
        .error-banner.show {
            display: block;
        }
        
        .error-banner h3 {
            margin-bottom: 8px;
            font-size: 18px;
            font-weight: 600;
        }
        
        .error-banner p {
            margin-bottom: 12px;
            font-size: 14px;
            opacity: 0.9;
        }
        
        .retry-button {
            background: white;
            color: #DC143C;
            border: none;
            padding: 8px 16px;
            border-radius: 8px;
            font-size: 14px;
            font-weight: 600;
            cursor: pointer;
            margin-top: 8px;
        }
        
        .retry-button:hover {
            opacity: 0.9;
        }
        
        .loading-indicator {
            position: absolute;
            top: 50%;
            left: 50%;
            transform: translate(-50%, -50%);
            background: rgba(255, 255, 255, 0.95);
            padding: 20px 30px;
            border-radius: 12px;
            z-index: 999;
            text-align: center;
            box-shadow: 0 4px 12px rgba(0,0,0,0.2);
            display: none;
        }
        
        .loading-indicator.show {
            display: block;
        }
        
        .spinner {
            border: 3px solid #f3f3f3;
            border-top: 3px solid #007AFF;
            border-radius: 50%;
            width: 30px;
            height: 30px;
            animation: spin 1s linear infinite;
            margin: 0 auto 12px;
        }
        
        @keyframes spin {
            0% { transform: rotate(0deg); }
            100% { transform: rotate(360deg); }
        }
        
        .bottom-nav {
            position: fixed;
            bottom: 0;
            left: 0;
            right: 0;
            background: white;
            border-top: 1px solid #e0e0e0;
            display: flex;
            justify-content: space-around;
            padding: 8px 0 max(8px, env(safe-area-inset-bottom));
            z-index: 1000;
            box-shadow: 0 -2px 10px rgba(0,0,0,0.1);
        }
        
        .nav-item {
            display: flex;
            flex-direction: column;
            align-items: center;
            padding: 4px 12px;
            cursor: pointer;
            text-decoration: none;
            color: #8e8e93;
            font-size: 10px;
            transition: color 0.2s;
        }
        
        .nav-item.active {
            color: #007AFF;
        }
        
        .nav-icon {
            width: 24px;
            height: 24px;
            margin-bottom: 4px;
            font-size: 22px;
        }
        
        .map-label {
            position: absolute;
            bottom: 80px;
            left: 12px;
            background: rgba(0, 0, 0, 0.6);
            color: white;
            padding: 6px 12px;
            border-radius: 8px;
            font-size: 16px;
            font-weight: 600;
            z-index: 500;
        }
        
        .leaflet-container {
            background: #e5e5e5;
        }
        
        .view-container {
            display: none;
            width: 100%;
            height: calc(100vh - 60px);
            overflow-y: auto;
            background: #f5f5f5;
            padding-bottom: 60px;
        }
        
        .view-container.active {
            display: block;
        }
        
        .navigation-view {
            padding: 20px;
            max-width: 600px;
            margin: 0 auto;
        }
        
        .navigation-header {
            margin-bottom: 24px;
        }
        
        .navigation-header h1 {
            font-size: 28px;
            font-weight: 600;
            color: #333;
            margin-bottom: 8px;
        }
        
        .navigation-header p {
            font-size: 14px;
            color: #666;
        }
        
        .route-inputs {
            background: white;
            border-radius: 12px;
            box-shadow: 0 2px 8px rgba(0,0,0,0.1);
            overflow: hidden;
            margin-bottom: 20px;
        }
        
        .input-row {
            display: flex;
            align-items: center;
            padding: 16px;
            border-bottom: 1px solid #e0e0e0;
        }
        
        .input-row:last-child {
            border-bottom: none;
        }
        
        .input-icon {
            width: 24px;
            height: 24px;
            margin-right: 12px;
            display: flex;
            align-items: center;
            justify-content: center;
            font-size: 18px;
        }
        
        .input-icon.start {
            color: #34C759;
        }
        
        .input-icon.end {
            color: #FF3B30;
        }
        
        .input-field {
            flex: 1;
            border: none;
            outline: none;
            font-size: 16px;
            color: #333;
            background: transparent;
        }
        
        .input-field::placeholder {
            color: #999;
        }
        
        .swap-button {
            background: #f5f5f5;
            border: none;
            padding: 8px;
            border-radius: 8px;
            cursor: pointer;
            margin: 8px 16px;
            display: flex;
            align-items: center;
            justify-content: center;
            font-size: 18px;
            transition: background 0.2s;
        }
        
        .swap-button:hover {
            background: #e0e0e0;
        }
        
        .action-buttons {
            display: flex;
            gap: 12px;
            margin-top: 24px;
        }
        
        .action-button {
            flex: 1;
            padding: 14px 24px;
            border: none;
            border-radius: 12px;
            font-size: 16px;
            font-weight: 600;
            cursor: pointer;
            transition: all 0.2s;
        }
        
        .action-button.primary {
            background: #007AFF;
            color: white;
        }
        
        .action-button.primary:hover {
            background: #0051D5;
        }
        
        .action-button.secondary {
            background: white;
            color: #007AFF;
            border: 1px solid #007AFF;
        }
        
        .action-button.secondary:hover {
            background: #f0f7ff;
        }
        
        .action-button:disabled {
            opacity: 0.5;
            cursor: not-allowed;
        }
    </style>
</head>
<body>
    <div id="map-container" class="view-container active">
        <div id="map"></div>
        <div class="map-label">Toronto</div>
        <div class="loading-indicator" id="loading">
            <div class="spinner"></div>
            <div>Loading risk data...</div>
        </div>
        <div class="error-banner" id="errorBanner">
            <h3>Error: The request timed out.</h3>
            <p>Toronto</p>
            <button class="retry-button" onclick="loadRiskData()">Retry</button>
        </div>
    </div>
    
    <div id="high-risk-view" class="view-container">
        <div style="padding: 20px; text-align: center; color: #666;">
            <h2>High Risk Areas</h2>
            <p>Coming soon...</p>
        </div>
    </div>
    
    <div id="settings-view" class="view-container">
        <div style="padding: 20px; text-align: center; color: #666;">
            <h2>Settings</h2>
            <p>Coming soon...</p>
        </div>
    </div>
    
    <div id="navigation-view" class="view-container">
        <div class="navigation-view">
            <div class="navigation-header">
                <h1>Navigation</h1>
                <p>Enter your starting point and destination</p>
            </div>
            
            <div class="route-inputs">
                <div class="input-row">
                    <div class="input-icon start">📍</div>
                    <input type="text" id="start-point" class="input-field" placeholder="Starting point" />
                </div>
                <button class="swap-button" id="swap-button" title="Swap start and destination">⇅</button>
                <div class="input-row">
                    <div class="input-icon end">🎯</div>
                    <input type="text" id="end-point" class="input-field" placeholder="Destination" />
                </div>
            </div>
            
            <div class="action-buttons">
                <button class="action-button secondary" id="clear-button">Clear</button>
                <button class="action-button primary" id="plan-route-button" disabled>Plan Route</button>
            </div>
        </div>
    </div>
    
    <div class="bottom-nav">
        <div class="nav-item active" data-view="map-container">
            <div class="nav-icon">🗺️</div>
            <div>Map</div>
        </div>
        <div class="nav-item" data-view="high-risk-view">
            <div class="nav-icon">⚠️</div>
            <div>High Risk</div>
        </div>
        <div class="nav-item" data-view="navigation-view">
            <div class="nav-icon">🧭</div>
            <div>Navigation</div>
        </div>
        <div class="nav-item" data-view="settings-view">
            <div class="nav-icon">⚙️</div>
            <div>Settings</div>
        </div>
    </div>
    
    <script>
        // Initialize map centered on Toronto
        const map = L.map('map', {
            zoomControl: true,
            attributionControl: false
        }).setView([43.6532, -79.3832], 12);
        
        // Add tile layer (Apple Maps style)
        L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
            attribution: '&copy; OpenStreetMap contributors',
            maxZoom: 19
        }).addTo(map);
        
        // Add attribution
        L.control.attribution({
            position: 'bottomright',
            prefix: false
        }).addTo(map);
        
        const riskColors = {
            'low': '#2E8B57',
            'medium': '#FFA500',
            'high': '#DC143C'
        };
        
        let roadPolylines = [];
        
        async function loadRiskData() {
            const loadingEl = document.getElementById('loading');
            const errorBanner = document.getElementById('errorBanner');
            
            loadingEl.classList.add('show');
            errorBanner.classList.remove('show');
            
            try {
                const bounds = map.getBounds();
                const requestBody = {
                    north: bounds.getNorth(),
                    south: bounds.getSouth(),
                    east: bounds.getEast(),
                    west: bounds.getWest()
                };
                
                const response = await fetch('/api/risk-predictions', {
                    method: 'POST',
                    headers: {
                        'Content-Type': 'application/json'
                    },
                    body: JSON.stringify(requestBody),
                    signal: AbortSignal.timeout(30000) // 30 second timeout
                });
                
                if (!response.ok) {
                    throw new Error(`HTTP error! status: ${response.status}`);
                }
                
                const segments = await response.json();
                
                // Clear existing polylines
                roadPolylines.forEach(line => map.removeLayer(line));
                roadPolylines = [];
                
                // Add road segments
                segments.forEach(segment => {
                    if (segment.coordinates && segment.coordinates.length > 0) {
                        const latlngs = segment.coordinates.map(coord => [coord.latitude, coord.longitude]);
                        const color = riskColors[segment.risk_label] || riskColors['low'];
                        
                        const polyline = L.polyline(latlngs, {
                            color: color,
                            weight: 4,
                            opacity: 0.8
                        }).addTo(map);
                        
                        roadPolylines.push(polyline);
                    }
                });
                
                loadingEl.classList.remove('show');
            } catch (error) {
                console.error('Error loading risk data:', error);
                loadingEl.classList.remove('show');
                errorBanner.classList.add('show');
                
                if (error.name === 'AbortError' || error.message.includes('timeout')) {
                    errorBanner.querySelector('h3').textContent = 'Error: The request timed out.';
                } else {
                    errorBanner.querySelector('h3').textContent = `Error: ${error.message}`;
                }
            }
        }
        
        // Load data when map moves
        let moveTimeout;
        map.on('moveend', () => {
            clearTimeout(moveTimeout);
            moveTimeout = setTimeout(() => {
                loadRiskData();
            }, 500);
        });
        
        // Initial load
        loadRiskData();
        
        // Tab navigation
        const navItems = document.querySelectorAll('.nav-item');
        const viewContainers = document.querySelectorAll('.view-container');
        
        navItems.forEach(item => {
            item.addEventListener('click', () => {
                const targetView = item.getAttribute('data-view');
                
                // Update active nav item
                navItems.forEach(nav => nav.classList.remove('active'));
                item.classList.add('active');
                
                // Show target view, hide others
                viewContainers.forEach(view => {
                    if (view.id === targetView) {
                        view.classList.add('active');
                    } else {
                        view.classList.remove('active');
                    }
                });
            });
        });
        
        // Navigation view functionality
        const startPointInput = document.getElementById('start-point');
        const endPointInput = document.getElementById('end-point');
        const swapButton = document.getElementById('swap-button');
        const clearButton = document.getElementById('clear-button');
        const planRouteButton = document.getElementById('plan-route-button');
        
        // Swap start and end points
        swapButton.addEventListener('click', () => {
            const startValue = startPointInput.value;
            const endValue = endPointInput.value;
            startPointInput.value = endValue;
            endPointInput.value = startValue;
            checkRouteButtonState();
        });
        
        // Clear inputs
        clearButton.addEventListener('click', () => {
            startPointInput.value = '';
            endPointInput.value = '';
            checkRouteButtonState();
        });
        
        // Check if route button should be enabled
        function checkRouteButtonState() {
            const hasStart = startPointInput.value.trim().length > 0;
            const hasEnd = endPointInput.value.trim().length > 0;
            planRouteButton.disabled = !(hasStart && hasEnd);
        }
        
        // Enable/disable route button based on input
        startPointInput.addEventListener('input', checkRouteButtonState);
        endPointInput.addEventListener('input', checkRouteButtonState);
        
        // Plan route button (placeholder - will be implemented later)
        planRouteButton.addEventListener('click', () => {
            const start = startPointInput.value.trim();
            const end = endPointInput.value.trim();
            if (start && end) {
                // Placeholder - route planning will be implemented later
                alert('Route planning will be implemented soon.\\n\\nStart: ' + start + '\\nEnd: ' + end);
            }
        });
    </script>
</body>
</html>
""", mimetype='text/html')


@app.route("/api/health", methods=["GET"])
def health_check():
    """Health check endpoint"""
    return jsonify(
        {
            "status": "healthy",
            "model_loaded": model_trainer is not None
            and model_trainer.model is not None,
            "preprocessed_data_loaded": preprocessed_data is not None,
            "road_network_loaded": road_network is not None,
            "preprocessed_segments": (
                len(preprocessed_data) if preprocessed_data is not None else 0
            ),
        }
    )


@app.route("/api/risk-predictions", methods=["POST"])
def get_risk_predictions():
    """
    Get risk predictions for a geographic region

    Request body:
    {
        "north": float,
        "south": float,
        "east": float,
        "west": float
    }
    """
    if model_trainer is None or model_trainer.model is None:
        return jsonify({"error": "Model not loaded"}), 500

    try:
        data = request.get_json()
        north = data.get("north")
        south = data.get("south")
        east = data.get("east")
        west = data.get("west")

        # use pre-processed data if available
        if preprocessed_data is not None:
            bbox = box(west, south, east, north)
            segments_in_bbox = preprocessed_data[
                preprocessed_data.geometry.intersects(bbox)
            ]

            # limit to 500 segments to prevent timeout and reduce response size
            # prioritize high-risk segments first
            if len(segments_in_bbox) > 500:
                # sort by risk level (high > medium > low) and take top 500
                risk_priority = {"high": 3, "medium": 2, "low": 1}
                segments_in_bbox = segments_in_bbox.copy()
                segments_in_bbox["_risk_priority"] = segments_in_bbox.get(
                    "risk_label", "low"
                ).map(risk_priority)
                segments_in_bbox = segments_in_bbox.sort_values(
                    "_risk_priority", ascending=False
                ).head(500)

            results = []
            for idx, segment in segments_in_bbox.iterrows():
                # extract coordinates from geometry
                coords = _extract_coordinates(segment.geometry)

                # use pre-processed risk prediction (already computed, no need to run model again)
                risk_label = segment.get("risk_label", "low")
                confidence = segment.get("confidence", 0.5)

                result = {
                    "id": str(segment.get("segment_id", idx)),
                    "LINEAR_NAME": segment.get("LINEAR_NAME", "Unknown"),
                    "ROAD_CLASS": segment.get("ROAD_CLASS", "Unknown"),
                    "segment_length": float(segment.get("segment_length", 0)),
                    "risk_label": risk_label,
                    "confidence": float(confidence) if confidence else 0.5,
                    "num_total_crashes": int(segment.get("num_total_crashes", 0)),
                    "num_ksi_crashes": int(segment.get("num_ksi_crashes", 0)),
                    "fatality_count": int(segment.get("fatality_count", 0)),
                    "coordinates": coords[:50],  # Limit coordinates to reduce payload
                }
                results.append(result)

            logging.info(f"Returning {len(results)} segments for bbox")
            return jsonify(results)

        # fallback: process on-demand
        elif road_network is not None:
            bbox = box(west, south, east, north)
            segments_in_bbox = road_network[
                road_network.geometry.intersects(bbox)
            ].head(100)

            # this would require full data processing pipeline, but, for now, returning basic info without predictions
            results = []
            for idx, segment in segments_in_bbox.iterrows():
                coords = _extract_coordinates(segment.geometry)

                result = {
                    "id": str(idx),
                    "LINEAR_NAME": segment.get("LINEAR_NAME", "Unknown"),
                    "ROAD_CLASS": segment.get("ROAD_CLASS", "Unknown"),
                    "segment_length": float(segment.get("segment_length", 0)),
                    "risk_label": "low",  # default, would need full processing
                    "confidence": 0.5,
                    "num_total_crashes": 0,
                    "num_ksi_crashes": 0,
                    "fatality_count": 0,
                    "coordinates": coords[:50],
                }
                results.append(result)

            return jsonify(results)
        else:
            return jsonify({"error": "Road network not loaded"}), 500

    except Exception as e:
        logging.error(f"Error in risk predictions: {e}")
        import traceback

        traceback.print_exc()
        return jsonify({"error": str(e)}), 500


def _extract_coordinates(geometry):
    """Extract coordinates from geometry for JSON serialization"""
    coords = []
    try:
        # Handle multi-part geometries (MultiLineString, MultiPoint, etc.)
        # Check for 'geoms' attribute first to avoid trying .coords on multi-part geometries
        if hasattr(geometry, "geoms") and geometry.geoms:
            for geom in geometry.geoms:
                # Each sub-geometry should be a LineString, Point, etc.
                if hasattr(geom, "coords"):
                    for coord in geom.coords:
                        if len(coord) >= 2:
                            lon, lat = coord[0], coord[1]
                            coords.append({"latitude": lat, "longitude": lon})
        # Handle single-part geometries (LineString, Point, etc.)
        elif hasattr(geometry, "coords"):
            for coord in geometry.coords:
                if len(coord) >= 2:
                    lon, lat = coord[0], coord[1]
                    coords.append({"latitude": lat, "longitude": lon})
        # Handle Polygon - get exterior coordinates
        elif hasattr(geometry, "exterior"):
            return _extract_coordinates(geometry.exterior)
        # Handle Polygon with xy attribute
        elif hasattr(geometry, "xy"):
            x_coords, y_coords = geometry.xy
            for lon, lat in zip(x_coords, y_coords):
                coords.append({"latitude": lat, "longitude": lon})
    except (AttributeError, TypeError, IndexError) as e:
        # Suppress warnings for expected geometry structure differences
        # These are handled by the code above, no need to log
        pass
    except Exception as e:
        # Only log truly unexpected errors, and at debug level
        logging.debug(f"Error extracting coordinates: {e}")
    return coords


def _predict_segment_risk(segment, model_trainer):
    """
    Get risk prediction from model for a segment

    Args:
        segment: GeoDataFrame row with segment data
        model_trainer: Loaded ModelTrainer instance

    Returns:
        Tuple of (risk_label, probabilities_dict, confidence) or (None, None, None) if prediction fails
    """
    try:
        # Check if segment has the required feature columns
        if not model_trainer.feature_columns:
            return None, None, None

        # Create a DataFrame with just this segment
        segment_df = pd.DataFrame([segment])

        # Extract features (only those used by the model)
        feature_data = {}
        for col in model_trainer.feature_columns:
            if col in segment_df.columns:
                value = segment_df[col].iloc[0]
                # Convert to numeric, handling various types
                if pd.isna(value):
                    feature_data[col] = 0.0
                else:
                    try:
                        feature_data[col] = float(value)
                    except (ValueError, TypeError):
                        feature_data[col] = 0.0
            else:
                feature_data[col] = 0.0

        X = pd.DataFrame([feature_data])

        for col in model_trainer.feature_columns:
            if col not in X.columns:
                X[col] = 0.0

        X = X[model_trainer.feature_columns]

        # scale features
        X_scaled = model_trainer.scaler.transform(X)

        # get prediction and probabilities
        prediction_encoded = model_trainer.model.predict(X_scaled)[0]
        probabilities_encoded = model_trainer.model.predict_proba(X_scaled)[0]

        risk_label = model_trainer.label_encoder.inverse_transform(
            [prediction_encoded]
        )[0]

        class_order = model_trainer.label_encoder.classes_
        probabilities = {
            "low": float(probabilities_encoded[0]),
            "medium": float(probabilities_encoded[1]),
            "high": float(probabilities_encoded[2]),
        }

        # Confidence is the maximum probability
        confidence = float(np.max(probabilities_encoded))

        return risk_label, probabilities, confidence

    except Exception as e:
        logging.warning(f"Error predicting segment risk: {e}")
        import traceback

        traceback.print_exc()
        return None, None, None


@app.route("/api/risk-prediction", methods=["POST"])
def get_risk_prediction():
    """
    Get risk prediction for a specific location

    Request body:
    {
        "latitude": float,
        "longitude": float
    }
    """
    if model_trainer is None or model_trainer.model is None:
        return jsonify({"error": "Model not loaded"}), 500

    try:
        data = request.get_json()
        lat = data.get("latitude")
        lon = data.get("longitude")

        point = Point(lon, lat)

        # Use pre-processed data if available
        if preprocessed_data is not None:
            # Find nearest segment
            from shapely.ops import nearest_points

            nearest_idx = None
            min_distance = float("inf")

            for idx, segment in preprocessed_data.iterrows():
                distance = point.distance(segment.geometry)
                if distance < min_distance:
                    min_distance = distance
                    nearest_idx = idx

            if nearest_idx is not None and min_distance < 0.01:  # Within ~1km
                segment = preprocessed_data.loc[nearest_idx]

                risk_label = segment.get("risk_label", "low")
                confidence = segment.get("confidence", 0.5)
                probabilities = None

                if model_trainer and model_trainer.model is not None:
                    try:
                        prediction, probs, model_confidence = _predict_segment_risk(
                            segment, model_trainer
                        )
                        if prediction is not None:
                            risk_label = prediction
                            confidence = model_confidence
                            probabilities = probs
                    except Exception as e:
                        logging.debug(f"Could not get model prediction: {e}")

                if probabilities is None:
                    if risk_label == "high":
                        probabilities = {"low": 0.1, "medium": 0.1, "high": 0.8}
                    elif risk_label == "medium":
                        probabilities = {"low": 0.2, "medium": 0.7, "high": 0.1}
                    else:
                        probabilities = {"low": 0.8, "medium": 0.15, "high": 0.05}

                segment_info = {
                    "id": str(segment.get("segment_id", nearest_idx)),
                    "LINEAR_NAME": segment.get("LINEAR_NAME", "Unknown"),
                    "ROAD_CLASS": segment.get("ROAD_CLASS", "Unknown"),
                    "segment_length": float(segment.get("segment_length", 0)),
                    "num_total_crashes": int(segment.get("num_total_crashes", 0)),
                    "num_ksi_crashes": int(segment.get("num_ksi_crashes", 0)),
                    "fatality_count": int(segment.get("fatality_count", 0)),
                    "coordinates": _extract_coordinates(segment.geometry),
                }

                response = {
                    "riskLevel": risk_label,
                    "confidence": float(confidence),
                    "probabilities": probabilities,
                    "segmentInfo": segment_info,
                }

                return jsonify(response)

        response = {
            "riskLevel": "low",
            "confidence": 0.5,
            "probabilities": {"low": 0.8, "medium": 0.15, "high": 0.05},
            "segmentInfo": None,
        }

        return jsonify(response)

    except Exception as e:
        logging.error(f"Error in risk prediction: {e}")
        import traceback

        traceback.print_exc()
        return jsonify({"error": str(e)}), 500


if __name__ == "__main__":
    logging.basicConfig(level=logging.INFO)
    app.run(host="0.0.0.0", port=8000, debug=True, use_reloader=False)
